### PR TITLE
Merge distutils fix for setting Py_GIL_DISABLED on Windows

### PR DESCRIPTION
**Pull request by lysnikolaou**
## Summary of changes

Related to #4662  and pypa/distutils#310.

### Pull Request Checklist
- [x] News fragment added in [`newsfragments/`].
  _(See [documentation][PR docs] for details)_

[`newsfragments/`]: https://github.com/pypa/setuptools/tree/master/newsfragments
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by Avasam** [comment]
Wouldn't this be automatically included with the next distutils sync ? https://setuptools.pypa.io/en/latest/development/developer-guide.html#code-conventions-and-other-practices

**Comment by MatthieuDartiailh** [comment]
@Avasam do you know when the sync will happen ? I am waiting on this fix to publish a new release of https://github.com/nucleic/kiwi.

**Comment by Avasam** [comment]
> @Avasam do you know when the sync will happen ? I am waiting on this fix to publish a new release of [nucleic/kiwi](https://github.com/nucleic/kiwi?rgh-link-date=2024-12-14T22%3A24%3A44Z).

That's a question for @jaraco

**Comment by Avasam** [comment]
This is now merged

**Pull request closed without merging**
