### PR TITLE
Remove test command

### LINKED ISSUE #931: Remove test command and tests_require
In [this comment](/pypa/setuptools/issues/917#issuecomment-274325745), @graingert proposes that we may be able to completely remove support for tests_require instead of transitioning that tooling from `easy_install` to `pip install`.

While he didn't directly propose removal, the effort would only benefit that ticket if the install functionality were completely removed, so let's explore what that will entail.

While I agree that `tox` is an excellent, powerful, robust solution, it's more heavy than `tests_require`, requiring that the user have tox installed in advance. As a more thorough solution, it also is subject to bugs and constraints that a simpler test runner is not. There are several advantages to `setup.py test` and `tests_require` over tox:

- Doesn't have any prerequisites (except the implicit one on Setuptools, which is generally assumed).
- As a result of not having any prerequisites, invocation is often a simple invocation (`setup.py test`) instead of multiple steps (e.g. `pip install --user tox; python -m tox`).
- `setup.py test` allows for invocation under a number of different Python versions naturally (i.e. `python3.3 setup.py test` or `py -3.3 setup.py test`) whereas tox offers "run under the python in which tox is installed" or "run for explicitly-declared python versions".
- As `setup.py test` doesn't use virtualenv, it's not subject to virtualenv bugs or other constraints imposed by virtualenv (such as version 14 dropping support for Python 3.2.).
- As `setup.py test` doesn't rely on pip, it's not subject to the bugs of pip (such as issues with `--editable` installs or namespace packages) or other constraints imposed by pip (such as dropping support for Python 3.2).

I consider these advantages small and easy enough to overcome, especially now that many of these issues have been resolved in setuptools, pip, and virtualenv. If we can get to a place that tox can broadly supplant the uses cases of setup.py test and [pytest-runner](https://pypi.org/project/pytest-runner) (and thus tests_require) in practice, then yes, deprecating and removing it would be in order. Given the amount of activity and bugs I see around these tools, I'd asses they're still in active use.

Before flagging this functionality as deprecated, I'd like to survey the community about the possibility to see if there are use cases that would prove difficult to support with tox.

@graingert, would you be interested in being the champion for this effort (removing tests_require), starting with the outreach on [distutils-sig](https://mail.python.org/mailman/listinfo/distutils-sig) and then implementing the deprecation/removal changes?

### PR DESCRIPTION
**Pull request by jaraco**
- **Move paths_on_pythonpath out of the command.test module.**
- **Remove test module and associated tests.**

## Summary of changes

Closes #931.

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`newsfragments/`].
  _(See [documentation][PR docs] for details)_

[`newsfragments/`]: https://github.com/pypa/setuptools/tree/master/newsfragments
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by bebound** [comment]
It seems some packages fails to install because of this change.
For example, `pip install vcrpy`.
```
Collecting vcrpy
  Downloading vcrpy-6.0.1.tar.gz (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 755.9 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wbp_9tw8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-wbp_9tw8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-wbp_9tw8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-wbp_9tw8/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by otms61** [comment]
The installation of the autobahn package also failed. Here is the error message:

```
> pip install autobahn
Collecting autobahn
  Using cached autobahn-23.6.2.tar.gz (480 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/saso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/saso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/saso/.pyenv/versions/3.11.4/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yg/56szr3gj3w504fzkc5851c9w0000gn/T/pip-build-env-6uyc5q5e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yg/56szr3gj3w504fzkc5851c9w0000gn/T/pip-build-env-6uyc5q5e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/yg/56szr3gj3w504fzkc5851c9w0000gn/T/pip-build-env-6uyc5q5e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/yg/56szr3gj3w504fzkc5851c9w0000gn/T/pip-build-env-6uyc5q5e/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 32, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by valentino-sm** [comment]
```
> pip wheel --no-cache-dir --use-pep517 nylas
Collecting nylas
  Downloading nylas-6.3.0.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/valentino/Developer/SellMeThisPen/vocode/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/valentino/Developer/SellMeThisPen/vocode/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/valentino/Developer/SellMeThisPen/vocode/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by kwongtn98** [comment]
`django-celery-beat` breaks too 

```
#33 [web build 8/8] RUN --mount=type=cache,target=/root/.cache/uv     if [ "dev" = "dev" ]; then         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements-dev.lock;     else         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements.lock;     fi
#33 3.182 error: Failed to download and build `django-celery-beat==2.6.0`
#33 3.182   Caused by: Failed to build: `django-celery-beat==2.6.0`
#33 3.183   Caused by: Build backend failed to determine extra requires with `build_wheel()` with exit status: 1
#33 3.183 --- stdout:
#33 3.183 
failed to solve: process "/bin/sh -c if [ \"$ENVIRONMENT\" = \"dev\" ]; then         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements-dev.lock;     else         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements.lock;     fi" did not complete successfully: exit code: 2
#33 3.183 --- stderr:
#33 3.183 Traceback (most recent call last):
#33 3.183   File "<string>", line 14, in <module>
#33 3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
#33 3.183     return self._get_build_requires(config_settings, requirements=[])
#33 3.183            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#33 3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
#33 3.183     self.run_setup()
#33 3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
#33 3.183     super().run_setup(setup_script=setup_script)
#33 3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
#33 3.183     exec(code, locals())
#33 3.183   File "<string>", line 9, in <module>
#33 3.183 ModuleNotFoundError: No module named 'setuptools.command.test'
#33 3.183 ---
#33 ERROR: process "/bin/sh -c if [ \"$ENVIRONMENT\" = \"dev\" ]; then         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements-dev.lock;     else         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements.lock;     fi" did not complete successfully: exit code: 2
------
 > [celeryworker build 8/8] RUN --mount=type=cache,target=/root/.cache/uv     if [ "dev" = "dev" ]; then         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements-dev.lock;     else         /root/.cargo/bin/uv pip install --no-cache-dir --system -r requirements.lock;     fi:
3.183            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
3.183     self.run_setup()
3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
3.183     super().run_setup(setup_script=setup_script)
3.183   File "/tmp/.tmpHvNSNa/builds-v0/.tmpf0XfAh/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
3.183     exec(code, locals())
3.183   File "<string>", line 9, in <module>
3.183 ModuleNotFoundError: No module named 'setuptools.command.test'
3.183 ---
------
```

**Comment by valentino-sm** [comment]
```
> pip wheel --no-cache-dir --use-pep517 nylas
Collecting nylas
  Downloading nylas-6.3.0.tar.gz (44 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/val/Developer/app/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/val/Developer/app/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/val/Developer/app/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/ml/yvwf_v0s3rs8h_b62psv0_5w0000gp/T/pip-build-env-i80m24b4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by anyidea** [comment]
`jsbeautifier` and `cssbeautifier` breaks too.

**Comment by PhuongTMR** [comment]
I encountered the same issue with `django-celery-beat==2.6.0` even though I have my `setuptools` version fixed at `69.1.1`. It's so weird. Please note that I'm using Poetry for installation.
```
#17 21.94   ChefBuildError
#17 21.94 
#17 21.94   Backend subprocess exited when trying to invoke get_requires_for_build_wheel
#17 21.94   
#17 21.94   Traceback (most recent call last):
#17 21.94     File "/app/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
#17 21.94       main()
#17 21.94     File "/app/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
#17 21.94       json_out["return_val"] = hook(**hook_input["kwargs"])
#17 21.94                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#17 21.94     File "/app/.local/share/pypoetry/venv/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
#17 21.94       return hook(config_settings)
#17 21.94              ^^^^^^^^^^^^^^^^^^^^^
#17 21.94     File "/tmp/tmpu16gtcd5/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
#17 21.94       return self._get_build_requires(config_settings, requirements=[])
#17 21.94              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#17 21.94     File "/tmp/tmpu16gtcd5/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
#17 21.94       self.run_setup()
#17 21.94     File "/tmp/tmpu16gtcd5/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
#17 21.94       super().run_setup(setup_script=setup_script)
#17 21.94     File "/tmp/tmpu16gtcd5/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
#17 21.94       exec(code, locals())
#17 21.94     File "<string>", line 9, in <module>
#17 21.94   ModuleNotFoundError: No module named 'setuptools.command.test'
#17 21.94   
#17 21.96 
#17 21.96   at .local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
#17 21.99       160│ 
#17 22.00       161│                 error = ChefBuildError("\n\n".join(message_parts))
#17 22.02       162│ 
#17 22.02       163│             if error is not None:
#17 22.02     → 164│                 raise error from None
#17 22.02       165│ 
#17 22.02       166│             return path
#17 22.03       167│ 
#17 22.03       168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
#17 22.05 
#17 22.05 Note: This error originates from the build backend, and is likely not a problem with poetry but with django-celery-beat (2.6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "django-celery-beat (==2.6.0)"'.
```

**Comment by FANGOD** [comment]
I have to temporarily use an older version of setuptools.
“”“
#10 18.71 Collecting SQLAlchemy==1.4.29 (from -r /tmp/requirements.txt (line 25))
#10 18.87   Downloading SQLAlchemy-1.4.29.tar.gz (8.0 MB)
#10 24.98      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 1.4 MB/s eta 0:00:00
#10 26.70   Preparing metadata (setup.py): started
#10 26.96   Preparing metadata (setup.py): finished with status 'error'
#10 26.97   error: subprocess-exited-with-error
#10 26.97   
#10 26.97   × python setup.py egg_info did not run successfully.
#10 26.97   │ exit code: 1
#10 26.97   ╰─> [6 lines of output]
#10 26.97       Traceback (most recent call last):
#10 26.97         File "<string>", line 2, in <module>
#10 26.97         File "<pip-setuptools-caller>", line 34, in <module>
#10 26.97         File "/tmp/pip-install-1243ft56/sqlalchemy_3f077010db4f461497398e0b7ffee028/setup.py", line 10, in <module>
#10 26.97           from setuptools.command.test import test as TestCommand
#10 26.97       ModuleNotFoundError: No module named 'setuptools.command.test'
#10 26.97       [end of output]
#10 26.97   
#10 26.97   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 27.71 error: metadata-generation-failed
#10 27.71 
#10 27.71 × Encountered error while generating package metadata.
#10 27.71 ╰─> See above for output.
#10 27.71 
#10 27.71 note: This is an issue with the package mentioned above, not pip.
#10 27.71 hint: See above for details.
#10 ERROR: process "/bin/sh -c pip --no-cache-dir install -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt" did not complete successfully: exit code: 1
------
 > [6/7] RUN pip --no-cache-dir install -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt:
26.97       [end of output]
26.97   
26.97   note: This error originates from a subprocess, and is likely not a problem with pip.
27.71 error: metadata-generation-failed
27.71 
27.71 × Encountered error while generating package metadata.
27.71 ╰─> See above for output.
27.71 
27.71 note: This is an issue with the package mentioned above, not pip.
27.71 hint: See above for details.
”“”

**Comment by gukoff** [comment]
Those for whom pinning `setuptools` doesn't help, try to downgrade pip to "pip<23.1.0".

On my machine, starting from `pip==23.1.0`, pip automatically fetches the latest setuptools during pip install. I'm trying to track down why.

**Pull request merged**
