### PR TITLE
Remove easy_install script and module.

### PR DESCRIPTION
**Pull request by jaraco**
## Summary of changes

Ref #917

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.readthedocs.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by emailweixu** [comment]
I am not sure if this is the right location to ask: I used to use easy_install to install eggs. How should I install 3rd-party eggs after easy_install script is removed. And I didn't find "pip install --egg" working.

**Comment by jaraco** [comment]
Your best bet is to stop installing eggs. There are lots of things that are bound to break going forward. Instead, build wheels and install them. If all you have are legacy eggs, consider building a tool to convert those to wheels.

No one is going to stop you from invoking easy_install as a setuptools command, but we won't be supporting that functionality and it could go away at any time (and will go away once setup_requires can be dropped).

**Comment by emailweixu** [comment]
> Your best bet is to stop installing eggs. There are lots of things that are bound to break going forward. Instead, build wheels and install them. If all you have are legacy eggs, consider building a tool to convert those to wheels.

Thanks for the reply. I tried using command "wheel convert" to convert the egg to wheel. But "pip install" failed to install the wheel and reported that the wheel "is not a supported wheel on this platform".  However, the egg can be successfully installed using the hacky method.

**Comment by learnereveryday** [comment]
@emailweixu Thank you so much! This hacky workaround is exactly what I have been looking for.

**Comment by jaraco** [comment]
If you need egg to wheel conversion, I'd bring that up with the wheel project and be prepared to have to provide your own fix. In #2908, I've drafted the removal of easy_install, which will break the hacky workaround. Once that's released, your recourse will be to:

- find a way to convert those eggs to wheels
- use older versions of setuptools to install the egg
- build wheels from source and install those (recommended)

**Comment by learnereveryday** [comment]
@jaraco Got it. Thanks for the info on what to expect. Yes, I think egg to wheel conversion utility tool will be quite helpful, as it is sometimes difficult for the third party enterprise packages in keeping up with the curve.

**Pull request merged**
