### PR TITLE
Add new hook 'setuptools.finalize_distribution_options'

### LINKED ISSUE #1055: no way to support setuptools plugin option in setup.cfg metadata
while experimenting with setuptools_scm metadata i discovered that there doesn't seem to be a way to add setup.cfg metadata support to setuptools plugins

### PR DESCRIPTION
**Pull request by jaraco**
## Summary of changes

Allows plugins like 'setuptools_scm' to alter distribution options (such as in pypa/setuptools_scm#364).

Closes #1055

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@jaraco thanks for beginning this, is there anything i can/should do to help bring this along

**Comment by jaraco** [comment]
Now that setuptools dogfoods this feature, it's covered by the existing tests.

**Comment by jaraco** [comment]
At this point, I'm prepared to accept this feature at least experimentally for setuptools_scm to leverage. I still have one lingering concern:

- Now that setuptools uses the entry points to finalize options, it's possible that finalization will happen in a different order than before. It's not obvious to me that the order of execution is important (for those operations that were previously hard-coded). I'd like not to specify the order of the operations if it's not important.

To that end, I've added this patch locally:

```diff
diff --git a/setuptools/dist.py b/setuptools/dist.py
index 44990431..b2bdc409 100644
--- a/setuptools/dist.py
+++ b/setuptools/dist.py
@@ -7,6 +7,7 @@ import re
 import os
 import warnings
 import numbers
+import random
 import distutils.log
 import distutils.core
 import distutils.cmd
@@ -734,8 +735,9 @@ class Distribution(_Distribution):
 
         def by_order(hook):
             return getattr(hook, 'order', 0)
-        eps = pkg_resources.iter_entry_points(hook_key)
-        for ep in sorted(eps, key=by_order):
+        eps = list(pkg_resources.iter_entry_points(hook_key))
+        random.shuffle(eps)
+        for ep in eps:
             ep.load()(self)
 
     def _finalize_setup_keywords(self):
```

And then run the tests several times, which gives me strong confidence that there's no order dependency on the built-in finalizers, so I'm comfortable leaving the default finalizers at the default order index of 0.

Paul, since you were looking at the reported ticket, would you review this change?

**Comment by RonnyPfannschmidt** [comment]
@jaraco awesome, this is great, cant wait to pull in the setuptools_scm follow-up and apply it to pytest/others

**Comment by agronholm** [comment]
Thanks, I started work on a similar patch but didn't make much headway. I'm relieved to see this is getting done.

**Pull request merged**
