### PR TITLE
Remove monkeypatching of _msvccompiler.

### PR DESCRIPTION
**Pull request by jaraco**
The monkeypatch indicates that the functionality was ported from Python 3.8, so the version in distutils should be adequate now.

I note that there have been some [changes to this module](https://github.com/pypa/setuptools/commits/4c990b9eab4d33faf517fcc2080662ebde0d2841/setuptools/msvc.py) since it was ported from Python 3.8, including:

- [x] Arm support #4555 (addressed by pypa/distutils#285)
- [x] requiresAny support #3950 (addressed by pypa/distutils#289)
- [x] VS/VC 2017 support #2663 (addressed by pypa/distutils#289) 
- [x] #2334 (addressed by pypa/distutils#289)
- [x] ~~https://github.com/pypa/setuptools/pull/1904~~ (this was the port from Python 3.8.0)

We'll want to have those issues supported by pypa/distutils ~~if not fully dropping support for stdlib distutils~~ before enacting this change.

~~Merge after #4606.~~

## Summary of changes

Closes 

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`newsfragments/`].
  _(See [documentation][PR docs] for details)_

[`newsfragments/`]: https://github.com/pypa/setuptools/tree/master/newsfragments
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by abravalheri** [comment]
There are probably some changes in setuptools/msvc.py that need to be portrait to distutils.

**Comment by jaraco** [comment]
I updated the description to highlight the relevant changes.



> We'll want to have those issues supported by pypa/distutils if not fully dropping support for stdlib distutils before enacting this change.

On further consideration, I think it's safe to force Windows users who need improved VC/VS support not to use distutils from the stdlib, so support in pypa/distutils should be adequate.

**Comment by jaraco** [comment]
I've added #1904 to the list of changes to review. There are a lot of changes in there that don't match with what's in distutils, presumably because distutils has evolved since Python 3.8. I'm hoping it's not the case that these additional behaviors (like those to `find_vcvarsall`) weren't subtly added in #1904.

**Comment by jaraco** [comment]
Oh, interesting. So it looks like the contents in msvc were indeed drawn from [3.8.0](https://github.com/python/cpython/blob/fa919fdf2583bdfead1df00e842f24f30b2a34bf/Lib/distutils/_msvccompiler.py#L99-L136) but that implementation changed dramatically throughout the 3.8 series (especially in https://github.com/python/cpython/commit/0d20364b132014eec609b900997c34779a4d548c). This means that although bugs were fixed in stdlib distutils, those fixes have been largely unavailable to Setuptools' users.

We do want to adopt the fixes that are applied in distutils (and not go backward on those changes).

That means that there's liable to be more churn when adopting this change than I'd like, as distutils can't be made a drop-in replacement for what setuptools users expect. Depending on the amount of disruption, we may need to yank releases or back out changes until the differences can be assessed.

**Comment by saschanaz** [comment]
> Arm support https://github.com/pypa/setuptools/pull/4555 (addressed by https://github.com/pypa/distutils/pull/285)

But those are independent, no? The former is to find vcvarsall and the latter is to get the right tool from that vcvarsal.

**Comment by saschanaz** [comment]
Oh, folded into https://github.com/pypa/setuptools/commit/196d44b8a1bd626764e9679c1b4b77ccc1d7ed3f. Never mind then.

**Comment by jaraco** [comment]
Thanks for reviewing. Please let me know how Setuptools 74 works for you. I'm happy to address any unexpected failures promptly.

**Comment by saschanaz** [comment]
The linked issues are unhappy with setuptools.msvc.EnvironmentInfo being removed, is there an equivalent now?

**Comment by jaraco** [comment]
There isn't. I did not realize they were in use. I was assuming and did not verify that those classes were only previously used for internal implementation details for functionality that had been removed.

Since users are relying on it, we should bring them back, and add some tests.

**Pull request merged**
