### PR TITLE
use abi3 extension if Extension().is_abi3

### PR DESCRIPTION
**Pull request by dholth**
Add an Extension(is_abi3=True) property that can be used to set its filename to something that will be loadable by more than one version of Python 3. An '.abi3.so' extension on Linux, just .pyd on Windows. Tested on Linux so far.

It will still be necessary to `-DPy_LIMITED_API=0x03030000` somewhere for the extension to truly be abi3.

### CODE REVIEW

**Comment by jaraco** [comment]
This patch appears to be failing on Python 3.

**Comment by jaraco** [comment]
Also, before adding a boolean parameter, is there a more descriptive parameter that could be added? Something like `binary_interface='abi3'` instead of `is_abi3=True`?

**Comment by dholth** [comment]
How about py_limited_api like the #ifdef, it could even be set to a version. py_limited_api = (3,3,0) or py_limited_api = 0x03030000.

**Comment by jaraco** [comment]
`py_limited_api` sounds fine. I think I like `(3,3,0)` better as it's more pythonic.

**Comment by dholth** [comment]
What if we let truthy set the extension, then reserve the tuple for future use (smart choice of wheel tags?) Similar to how 1 sets the basic feature in C.

**Comment by jaraco** [comment]
It feels to me like `abi3` appears to much in the implementation. Can we remove the `3` so that the implementation would work for future Pythons with a new ABI version?

**Comment by dholth** [comment]
I think abi3 is correct. The idea is that abi3 with Python 3.3 features works on all later versions of Python (it was introduced in py3.2, and 3.3 specifically adds some functions that were forgotten). (The extension doesn't say anything about the minimum Python ver

**Comment by dholth** [comment]
The other default abi is of course the "exactly this version of Python" default.

**Comment by jaraco** [comment]
Hi dholth. Sorry I missed your IRC messages when you sent them. Is this ready to go? Would you add a changelog entry for it?

**Comment by dholth** [comment]
It's ready to go if you don't have any better ideas for the name (which I think is a reasonable name). Would be happy to add a changelog entry.

**Pull request merged**
