### PR TITLE
use --depth 1 for git clone + use separate git fetch to download rev

### LINKED ISSUE #1446: easy_install: use --depth 1 with git clone when downloading requirements
Currently, when fetching requirements via `git`, `easy_install` fetches the complete git history. This can take very long for large repos.

To fix this, we can use `--depth 1` when doing `git clone` and subsequently do a `git fetch --depth 1 origin <rev>` to download a specific revision.

I already prepared a [branch](https://github.com/pypa/setuptools/compare/master...ubunatic:shallow-git-clone?expand=1) to fix this, and I am preparing a PR just now (following the PR instructions).

I tested my branch already with a private repo using
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git@master`
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git`

to check the `rev is None` and `rev is not None` code-paths.

### PR DESCRIPTION
**Pull request by ubunatic**
## Summary of changes

- use `--depth 1` with `git clone` to get a shallow clone of a required repo
- use a separate `git fetch --depth 1` to fetch a specific revision from the shallow clone

Closes #1446

### Pull Request Checklist
- [ ] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### Manual Tests
I did not find any git-download tests to extend and currently only tested manually using:
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git@master`
- `python3.6 -m easy_install --user -v git+ssh://git@github.com/private/repo.git`

### CODE REVIEW

**Comment by ubunatic** [comment]
closing, since this is already [discussed](https://github.com/pypa/pip/issues/2432) in pip

**Comment by mrx23dot** [comment]
What was the conclusion? It's still not implemented in 2022.

**Comment by ubunatic** [comment]
There was some discussion about ways to configure it in the URL, but I do not know the status of that (see: https://github.com/pypa/pip/issues/2432#issuecomment-363901451).
At least having it as default is off the table to safe backwards compatibility.

**Comment by mrx23dot** [comment]
Thanks, we can always manually git clone a shallow one and install it locally in case repo is huge.

**Pull request closed without merging**
