### PR TITLE
Improve badges in README

### PR DESCRIPTION
**Pull request by pradyunsg**
✨ 

* Consistent Styling
* Add Logos of CI services
* Shorten CI badge labels
* Reorder for better wrapping

### Pull Request Checklist
- [x] Changes have tests
  - Not needed
- [x] News fragment added in changelog.d.
  - Not needed

### CODE REVIEW

**Comment by pradyunsg** [comment]
GitHub's rich diffs aren't suited for this kind of change -- I suggest viewing the file via the "View File" button under the "Review Changes" button in the Files tab.

**Comment by pganssle** [comment]
By the way, the only reason I have not merged this is that I am waiting a bit until I have time to figure out why the coverage decreased here and whether the README is being counted under the coverage.

**Comment by pganssle** [comment]
I'm going to chalk this up to some weirdness with codecov, because it explicitly says that the README is not covered and the only thing it's pointing to as a difference in code coverage is a section of code that has definitely been non-covered for at least months, probably forever, so I'm going to go ahead and merge this.

**Comment by pradyunsg** [comment]
Thanks @pganssle and @jaraco!

**Pull request merged**
