### PR TITLE
Respect SOURCE_DATE_EPOCH when taring sdist.

### PR DESCRIPTION
**Pull request by Carreau**
This pulls just enough of distutils' and modify the make_tarball
function in order to respect SOURCE_DATE_EPOCH; this will ensure that
_when set_ no timestamp in the final archive is greater than timestamp.

This allows (but is not always sufficient), to make bytes for bytes
reproducible build for example:

 - This does not work with `gztar`, and zip does embed a timestamp in
 the header which currently is `time.time()` in the standard library.

 - if some fields passed to setup.py have on determinstic ordering (for
 example using sets for dependencies).

 Partial work toward #2133, with this I was able to make two bytes-identical
 sdist of IPython.

## Summary of changes

pull many function as-is from distutils with the exception of make_tarball to which a couple of lines are added. 

### Pull Request Checklist
- [ ] Changes have tests
- [ ] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

No tests yet, nor changelog, I want to make sure this is the right approach first.

### CODE REVIEW

**Comment by jaraco** [comment]
This is great. Thanks for putting this together.

I would recommend one change to your approach - if you could separate the commits of (a) copying code from distutils from (b) tweaking that code, it will make it easier to later reconcile any differences that might need to be merged from the original.

As is, if I try to review this, I can't tell what functionality was copied and what was changed. If you can separate those changes in the commit history, I'm pretty sure the changes here are acceptable.

As a side note, there is a larger effort to [incorporate all of distutils](https://github.com/pypa/setuptools/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Adopt+Distutils+and+stop+monkeypatching+stdlib%22), which if implemented would have made this change more straightforward.

**Comment by Carreau** [comment]
Yes, I can do this, no problem. The one issue though will be flake 8 will complain about the raw `distutils` code, but it should be pretty straitforward.

**Comment by Carreau** [comment]
Force-pushed with proper commit descriptions. I'd appreciate a pointer to a test that check a tar (not tar.gz as those are not yet reproducible), and can modify it to make sure the hash can be reproduced.

**Comment by benoit-pierre** [comment]
Have you checked #1512?

**Comment by Carreau** [comment]
I have not, but thanks, you definitely found the same issues that I did, though I went for much smaller and only tackle the minimal amount in one PR. 

I'll likely get inspiration from your tests.

**Comment by kushaldas** [comment]
Any update on this?

**Comment by jaraco** [comment]
@Carreau From your last comment, it wasn't clear to me whether you wanted to do more work on this or not. Can you clarify what the status is of this request?

**Comment by jaraco** [comment]
I'm closing this for now, but happy to revive the effort at any point.

**Pull request closed without merging**
