### PR TITLE
Prefer included distutils even without importing setuptools. Closes #2259.

### LINKED ISSUE #2259: Reconsidering distutils replacement strategy
I first expressed concerns about the fact that `distutils` needs to be imported *after* `setuptools` in [this post](https://github.com/pypa/setuptools/pull/2143#issuecomment-637586551), and I did not realize that we had not adequately addressed this before the `distutils` adoption. I think we should re-consider the way this is done, to avoid any sort of requirement on the sort order.

Currently, when you `import setuptools`, [`distutils` is injected into `sys.modules`](https://github.com/pypa/setuptools/blob/37d81f4ce8f08c4baf44b6ff0f3f1bd3f6b2a127/setuptools/distutils_patch.py#L48-L61).

The problem here is that it requires importing `setuptools` before `distutils`, which most people will *not* be doing right now (by almost all common import sort orders, `distutils` comes first).

@jaraco [explains why it's done this way here](https://github.com/pypa/setuptools/issues/2230#issuecomment-657327796):

> I did consider another approach, where Setuptools could add a .pth file that would import setuptools.distutils_patch. Such an approach would always happen earlier and so would not be subject to the race that's happening here, but it would also happen whether or not setuptools was imported (on any invocation of Python in that environment).

I think one preferred solution would be for us to install a `distutils` package that would be imported before `distutils`. The problem is that in the standard `sys.path`, `site-packages` comes *after* the standard library. Since anything we do here will be a tremendous hack, I'm thinking that maybe the most surgical way to accomplish this is to do something like this:

1. Create a `setuptools._distutils/import_hack/distutils/__init__.py` (where there's no `__init__.py` in `import_hack`) that invokes `import setuptools.distutils_patch`.
2. Add a `.pth` file that injects `$SITEPACKAGES/setuptools/_import_hack/` into `sys.path` *before* the standard library.

Another option I think we should consider is stepping up the timetable on providing everything `distutils` provides directly from the `setuptools` namespace, [as I described here](https://github.com/pypa/setuptools/pull/2143#issuecomment-637586551):

> I personally would prefer it if we made the setuptools namespace the canonical namespace, and have distutils just import symbols from setuptools and possibly wrap them in deprecation warnings.

Right now, there are things that you *must* import from `distutils`, and so we can't say, "You can avoid an issue with the sort order by just not importing `distutils`". If we provide everything that `distutils` provides in the `setuptools` namespace, we can just say, "Just use the `setuptools` version and you won't have this problem."

Personally, I think we should do a combination of both — make it so importing `distutils` still works in whatever order you do it in *and* move everything to the canonical `setuptools` namespace. That will make it easier to actively deprecate direct use of `distutils`, and pave the way for us eventually removing the need for the `.pth` file (though the fastest road to not having the `.pth` file will be via removing `distutils` from the standard library).

### PR DESCRIPTION
**Pull request by jaraco**
## Summary of changes

In #2259, Paul outlines the problem - users that import distutils before importing setuptools, a common if not recommended practice, will receive a warning and will end up with objects from different implementations of distutils.

When enabled, this change installs a .pth file (except for editable installs of setuptools) to the user's environment to ensure that the setuptools-provided distutils is preferred before setuptools has been imported (and even if setuptools is never imported).

This feature relies on the same SETUPTOOLS_USE_DISTUTILS flag for opt-in now and opt-out in the future (set to "local" for opt-in and "stdlib" for opt-out).

This patch was originally submitted as #2260 but backs out the refactoring that left the implementation in an unsuitable state.

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by pganssle** [comment]
Per my comments in #2260, I strongly disagree with this course of action. I don't think we should move forward with this change without testing, and even if we did, I think we should at least clean up the history so it's easier to revert specific subsets of the changes if necessary.

**Comment by jaraco** [comment]
I very much respect your opinion @pganssle, so I'm going to take another stab at writing a suite of tests for the distutils expectation.

**Comment by jaraco** [comment]
In #2315, I've written three tests that capture the user-facing behavior, including xfailing on the limitation identified in #2259. I expect that test to start xpassing with this change.

**Comment by jaraco** [comment]
I observe that the tests are failing on Windows, even though I thought they were passing in the previous PR. The test failures are in `test_virtualenv.test_pip_upgrade_from_source`. It's possible I missed this failure before because I mis-recognized the failure in appveyor as a "fail fast" (where it stops running and marks as fail if a newer version is pushed). Regardless, we'll need to investigate that issue too.

**Comment by jaraco** [comment]
The error occurs when it tries to run `sdist` and fails with this error:

```
error: could not create 'build\bdist.win-amd64\wheel\.\import os; enabled = os.environ.get('SETUPTOOLS_USE_DISTUTILS') == 'local'; enabled and __import__('_distutils_hack').add_shim(); \easy_install.py': No such file or directory
```

It seems the `_restore_install_lib` method isn't working properly under Windows.

**Comment by jaraco** [comment]
Here are the values of install_lib and install_libbase during the execution:

```
{'install_lib': 'build\\bdist.win-amd64\\wheel\\.\\import os; enabled = '
                "os.environ.get('SETUPTOOLS_USE_DISTUTILS') == 'local'; "
                "enabled and __import__('_distutils_hack').add_shim(); ",
 'install_libbase': 'build\\bdist.win-amd64\\wheel\\.'}
```

**Comment by jaraco** [comment]
Weird - I notice that suffix has no space at the end:

```
'suffix': "import os; enabled = os.environ.get('SETUPTOOLS_USE_DISTUTILS') == 'local'; enabled and __import__('_distutils_hack').add_shim();"
```

But when I run it locally, I get a different result:

```
>>> install_lib = "build\\bdist.win-amd64\\wheel\\.\\import os; enabled = os.environ.get('SETUPTOOLS_USE_DISTUTILS') == 'local'; enabled and __import__('_distutils_hack').add_shim(); "
>>> install_libbase = 'build\\bdist.win-amd64\\wheel\\.'
>>> ntpath.relpath(install_lib, install_libbase)
"import os; enabled = os.environ.get('SETUPTOOLS_USE_DISTUTILS') == 'local'; enabled and __import__('_distutils_hack').add_shim(); "
```

**Comment by jaraco** [comment]
Well, that's annoying. The pypy3 tests on macOS only are failing the new test. I guess that's expected, since we know pypy imports stdlib distutils on startup.

**Comment by pganssle** [comment]
Hmm, is that because it imports distutils before the pth file is executed?

**Comment by jaraco** [comment]
> Hmm, is that because it imports distutils before the pth file is executed?

That's right.

```
$ pypy3 -V
Python 3.6.9 (?, Apr 18 2020, 02:46:07)
[PyPy 7.3.1 with GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.59)]
$ pypy3 -S -c "import sys; print('distutils' in sys.modules)"
False
$ pypy3 -c "import sys; print('distutils' in sys.modules)"
True
```

If I recall correctly (low confidence), pypy for Python 3.7 no longer has this issue.

But here's something weird:

```
$ pypy3 -S -c "import site, sys; print('distutils' in sys.modules)"
False
```

I thought the only thing `-S` did was skip `import site`.

**Comment by jaraco** [comment]
[TIL](https://docs.python.org/3/using/cmdline.html#id3):

> -S: Disable the import of the module site and the site-dependent manipulations of sys.path that it entails. Also disable these manipulations if site is explicitly imported later (call site.main() if you want them to be triggered).

**Comment by jaraco** [comment]
```
~ $ pypy3 -S -c "import site, sys; site.main(); print('distutils' in sys.modules)"
True
```

**Comment by jaraco** [comment]
It's the calling of `sysconfig.getconfigvar` that causes the import of distutils:

```
$ pypy3 -S -c "import sys, sysconfig; print('distutils' in sys.modules); sysconfig.get_config_var('foo'); print('distutils' in sys.modules
)"
False
True
```

**Comment by jaraco** [comment]
Right - now I remember:

```
$ pypy3 -S -c "import sys, _sysconfigdata; print('distutils' in sys.modules)"
True
```

**Comment by jaraco** [comment]
It does appear that even on the unreleased PyPy for Python 3.7 [still imports distutils early](https://foss.heptapod.net/pypy/pypy/-/blob/401b5d80b19d7ada416d37509471da4b67c6fdfa/lib_pypy/_sysconfigdata.py#L4).

**Comment by jaraco** [comment]
Perhaps there are some optimizations or tweaks we can make for PyPy, but for now, I'd prefer to push forward with this approach.

**Comment by jaraco** [comment]
Released as 49.3.0

**Comment by gaborbernat** [comment]
This PR shouldn't have closed the issue. The issue is not fixed and manifests just as it did before. It's now only able to be bypassed by setting an environment variable. So to fix it still requires me an arbitrary environment variable change in my code...

**Comment by jaraco** [comment]
Thanks Bernát, though I'm not sure I follow. #2259 reported an issue that _when_ the new distutils is included, it only works when setuptools is imported prior to importing distutils. This patch fixed that condition. #2259 was not about ensuring that distutils was preferred in all environments, though that's still a goal.

I have added new issues to [the milestone](https://github.com/pypa/setuptools/milestone/5) to capture ongoing efforts. If that doesn't capture the missed use-cases, please elaborate.

**Pull request merged**
