### PR TITLE
utils: remove trailing whitespace

### PR DESCRIPTION
**Pull request by stepshal**

### CODE REVIEW

**Comment by jaraco** [comment]
Please remove the changes to py parsing. That package is maintained elsewhere.

**Comment by stepshal** [comment]
@jaraco changes to setuptools/utils.py  are already mix up in #634 by accident. So no point in this PR.

**Comment by stepshal** [comment]
@jaraco Done.

**Comment by stepshal** [comment]
@jaraco Done.

**Comment by stepshal** [comment]
@jaraco Done.

**Pull request merged**
