### PR TITLE
on Windows when setuptools is imported, appdirs is imported and in turn will lock pywin32's dlls

### PR DESCRIPTION
**Pull request by costypetrisor**
## Summary of changes

on Windows when `setuptools` is imported, `appdirs` is imported and in turn it will import `pywin32` if available, which will lock `pywin32`'s dlls and because of that `pywin32` cannot be updated anymore (your pip install command will fail too)

fix is to apply the same patch as the `pip` project did in     https://github.com/pypa/pip/pull/4992

Sample error output:
```
Consider using the `--user` option or check the permissions.
Traceback (most recent call last):
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\commands\install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\wheel.py", line 324, in move_wheel_files
    clobber(source, lib_dir, True)
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\wheel.py", line 295, in clobber
    os.unlink(destfile)
WindowsError: [Error 5] Access is denied: 'D:\\temp\\test_venv\\v27\\Lib\\site-packages\\win32\\win32api.pyd'
```

### Pull Request Checklist
- [ ] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by pganssle** [comment]
Can this patch be pushed upstream? It seems like in the 6 months or so since the pip patch no one has submitted a PR to appdirs.

**Comment by benoit-pierre** [comment]
This disable support for using pywin3, I imagine there's a reason it's the default? Also the `_get_win_folder_with_pywin32` is dead code now. So I don't thing this can be upstreamed (or that it will be accepted). Can you give more detail about the exact use case? What's the command being used?

**Comment by costypetrisor** [comment]
@benoit-pierre 
This is quite a nasty issue for Windows users. It's really easy to run into it, and when you run into it the only solution is to either recreate the virtualenv (not possible if you do this in the main interpreter) or to poke through the virtualenv and manually delete `pywin32`'s `dll`-s and `pyd`-s before trying again.

The issue happens when you have one version of `pywin32` installed and you wish to upgrade it, or instead of upgrading you install a package that requires a different `pywin32` version.

For most of the people it's probably not an issue to delete and recreate the venv, but for some (like my use case) who have a deploy pipeline where large virtualenvs are upgraded in place with new package version, this issue is a show stopper.

So to give an example, let's say you have pywin32 already installed:
```
D:\temp\test_venv>v27\Scripts\python.exe -m pip install pypiwin32==219
Looking in indexes: [...]
Collecting pypiwin32==219
  Downloading https://pypi.[...]/root/wheelhouse/+f/561/8522ad9c2b229/pypiwin32-219-cp27-none-win32.whl (
6.7MB)
    100% |UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU| 6.7MB 3.9MB/s
Installing collected packages: pypiwin32
Successfully installed pypiwin32-219
```

and then you wish to upgrade it, or you wish to install/upgrade a package which requires a different pywin32 version:
```
D:\temp\test_venv>v27\Scripts\python.exe -v -m pip install -vvv pywin32==223
[...]
Installing collected packages: pywin32

Could not install packages due to an EnvironmentError.
Consider using the `--user` option or check the permissions.
Traceback (most recent call last):
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\commands\install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\req\req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\wheel.py", line 324, in move_wheel_files
    clobber(source, lib_dir, True)
  File "D:\temp\test_venv\v27\lib\site-packages\pip\_internal\wheel.py", line 295, in clobber
    os.unlink(destfile)
WindowsError: [Error 5] Access is denied: 'D:\\temp\\test_venv\\v27\\Lib\\site-packages\\win32\\win32api.pyd'
Cleaning up...
Removed build tracker 'c:\\users\\myuser\\appdata\\local\\temp\\pip-req-tracker-vwsv63'
```

It's unfortunate that there are many places that during a `pip install` could load the `pywin32` dlls.

It used to be in `pip`, but they patched their `appdirs` module to not do so.

But unfortunately `pip` imports `setuptools` whose `appdirs` module (inside `pkg_resources`) does load the `pywin32` dlls. So you're stuck.

Another example of code that loads `pywin32` dlls during `pip install` is the `platform` module from Python's stdlib. A `setup.py` I had used the `platform` module, but I managed to remove the usage.

**Comment by benoit-pierre** [comment]
But pip does not import setuptools, and has its own vendored copy of pkg_resources.

**Comment by benoit-pierre** [comment]
What version of pip are you using?

**Comment by costypetrisor** [comment]
I'm using pip 10.0.1 and 18.0.

I've been a bit unclear, it's not about pip directly importing setuptools, it's about setuptools being imported in the pip process.

This can happen when you have a setup.py which imports (as recommended) `setup` from `setuptools`:

```
from setuptools import setup

setup(
    name='funniest',
    version='0.1',
    install_requires=[
        'pywin32==223',
    ],
    zip_safe=False,
)
```

In this example, this `funniest` package is even requesting a newer minimum version of `pywin32` compared to what I have in the venv already (219), and when I install this via `v27\Scripts\python.exe -v -m pip install -e pkg` I get:

```
Looking in indexes: https://pypi.[...]/rendezvous/dev, https://pypi.[...]/rendezvous/dev, https://pypi.[...]/rendezvous/dev
Obtaining file:///D:/temp/test_venv/pkg
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\temp\test_venv\v27\lib\site-packages\setuptools\__init__.py", line 12, in <module>
        import setuptools.version
      File "D:\temp\test_venv\v27\lib\site-packages\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "D:\temp\test_venv\v27\lib\site-packages\pkg_resources\__init__.py", line 73, in <module>
        from pkg_resources.extern import appdirs
      File "D:\temp\test_venv\v27\lib\site-packages\pkg_resources\extern\__init__.py", line 43, in load_module
        __import__(extant)
      File "D:\temp\test_venv\v27\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 510, in <module>
        raise Exception("this should not execute during pip install because it locks pywin32 dlls")
    Exception: this should not execute during pip install because it locks pywin32 dlls
    
    ----------------------------------------
``` 

I added this exception to show `appdirs.py` from `pkg_resources` gets imported during a pip install.

**Comment by costypetrisor** [comment]
Indeed `setup.py` files are import from a subprocess created by pip to fetch the egg info, Perhaps my impression that they were run from the same process is from a much older codebase of pip.

The first time I debugged this was a couple of months ago and it was in pip 9 (so pip didn't had the appdirs patch at that time) and that is when I first saw appdirs being imported which in turn would import the pywin32 dlls.

But I kept investigating today, and something is still wrong, because if I have a venv with pywin32 219 already installed, and then I install pywin32 223, then not all dlls are updated:

```
$  ./install.sh
+ v27/Scripts/python.exe -m pip install -U pywin32==223
Looking in indexes: https://pypi.[...]/rendezvous/dev, https://pypi.[...]/rendezvous/dev, https://pypi.[...]/rendezvous/dev
Collecting pywin32==223
  Downloading https://pypi.[...]/root/pypi/+f/42f/48567e36b7879/pywin32-223-cp27-cp27m-win32.whl (6.8MB)
Installing collected packages: pywin32
Could not install packages due to an EnvironmentError: [Error 5] Access is denied: 'D:\\temp\\test_venv\\v27\\Lib\\site-packages\\win32\\win32api.pyd'
Consider using the `--user` option or check the permissions.

+ rc=1
+ echo ---- rc=1
---- rc=1

MINGW64 /d/temp/test_venv
$  ./verify.sh
+ py -3.6 find_pywin32_version.py v27
---------- VENV: v27 -----------------
{'wheels\\pypiwin32-219-cp27-none-win32.whl': ['pythonwin\\mfc90.dll',
                                               'pythonwin\\mfc90u.dll',
                                               'pythonwin\\mfcm90.dll',
                                               'pythonwin\\mfcm90u.dll',
                                               'pythonwin\\scintilla.dll',
                                               'pywin32_system32\\pythoncomloader27.dll',
                                               'win32\\_win32sysloader.pyd',
                                               'win32\\_winxptheme.pyd',
                                               'win32\\win32api.pyd',
                                               'win32\\win32clipboard.pyd',
                                               'win32\\win32console.pyd',
                                               'win32\\win32cred.pyd',
                                               'win32\\win32crypt.pyd',
                                               'win32\\win32event.pyd',
                                               'win32\\win32evtlog.pyd',
                                               'win32\\win32file.pyd',
                                               'win32\\win32gui.pyd',
                                               'win32\\win32help.pyd',
                                               'win32\\win32inet.pyd',
                                               'win32\\win32job.pyd',
                                               'win32\\win32lz.pyd',
                                               'win32\\win32net.pyd',
                                               'win32\\win32pdh.pyd',
                                               'win32\\win32pipe.pyd',
                                               'win32\\win32print.pyd',
                                               'win32\\win32process.pyd',
                                               'win32\\win32profile.pyd',
                                               'win32\\win32ras.pyd',
                                               'win32\\win32security.pyd',
                                               'win32\\win32service.pyd',
                                               'win32\\win32trace.pyd',
                                               'win32\\win32transaction.pyd',
                                               'win32\\win32ts.pyd',
                                               'win32\\win32wnet.pyd',
                                               'win32\\winxpgui.pyd',
                                               'win32comext\\adsi\\adsi.pyd',
                                               'win32comext\\authorization\\authorization.pyd',
                                               'win32comext\\axcontrol\\axcontrol.pyd',
                                               'win32comext\\axdebug\\axdebug.pyd',
                                               'win32comext\\axscript\\axscript.pyd',
                                               'win32comext\\bits\\bits.pyd',
                                               'win32comext\\ifilter\\ifilter.pyd',
                                               'win32comext\\internet\\internet.pyd',
                                               'win32comext\\mapi\\mapi.pyd',
                                               'win32comext\\propsys\\propsys.pyd',
                                               'win32comext\\shell\\shell.pyd',
                                               'win32comext\\taskscheduler\\taskscheduler.pyd'],
 'wheels\\pypiwin32-219-cp27-none-win_amd64.whl': ['win32\\mmapfile.pyd'],
 'wheels\\pywin32-223-cp27-cp27m-win32.whl': ['isapi\\PyISAPI_loader.dll',
                                              'pythonwin\\dde.pyd',
                                              'pythonwin\\win32ui.pyd',
                                              'pythonwin\\win32uiole.pyd',
                                              'pywin32_system32\\pythoncom27.dll',
                                              'pywin32_system32\\pywintypes27.dll',
                                              'win32\\odbc.pyd',
                                              'win32\\perfmon.pyd',
                                              'win32\\perfmondata.dll',
                                              'win32\\servicemanager.pyd',
                                              'win32\\timer.pyd',
                                              'win32\\win2kras.pyd']}
```
(invoked from git-bash on windows so I can see the exit code easier)

Because there is no sane way to know which pywin32 is attributed to each dll from the virtualenv I made my own script which finds the dll sizes and for reference I attached it.

install.sh
```
#!/bin/bash

set -x

# v27/Scripts/python.exe -v -m pip install -e pkg 2> stderr.log 1> stdout.log
# v27/Scripts/python.exe -v -m pip install -U pywin32==223 2> stderr.log 1> stdout.log
v27/Scripts/python.exe -m pip install -U pywin32==223

rc=$?
echo ---- rc=$rc
```
verify.sh
```
#!/bin/bash
set -euxo pipefail
py -3.6 find_pywin32_version.py v27
```

[find_pywin32_version.zip](https://github.com/pypa/setuptools/files/2242028/find_pywin32_version.zip)


What's also interesting is that if I run with `python -v -m pip install ...` so `-v` to python not pip, then in stderr I can see which modules are imported, and even though this is from pip 18, `win32api.pyd` and others are imported:
```
import pip._internal.commands.wheel # precompiled from D:\temp\test_venv\v27\lib\site-packages\pip\_internal\commands\wheel.pyc
import win32api # dynamically loaded from D:\temp\test_venv\v27\lib\site-packages\win32\win32api.pyd
# D:\temp\test_venv\v27\lib\site-packages\win32\lib\win32con.pyc matches D:\temp\test_venv\v27\lib\site-packages\win32\lib\win32con.py
```

My investigation will continue tomorrow ...

**Comment by jaraco** [comment]
I'm loathe to accept patches to vendored code. This project is not interested in maintaining forks of vendored code. Only official releases are allowed in the vendored code. We do this in part because setuptools supports devendoring these packages.

Therefore, I recommend one of two approaches:

1. Shepherd the changes upstream. Once a release is made, setuptools will happily update its vendored code.
2. Setuptools should monkeypatch the undesirable behavior in its own code.

**Comment by jaraco** [comment]
I'm going to decline this patch, but I welcome a patch that takes one of the above approaches, assuming an investigation reveals that this is still needed.

**Pull request closed without merging**
