### PR TITLE
ignore .tox in pytest

### PR DESCRIPTION
**Pull request by minrk**
avoids errors in setup.py test if tox has been run

### CODE REVIEW

**Comment by minrk** [comment]
Rebased on #695 to get travis running again

**Comment by minrk** [comment]
Rebased on master, now.

**Comment by jaraco** [comment]
Ugh. I'm unable to manually resolve merge conflicts because I use hg-git, which has [a bug](https://bitbucket.org/durin42/hg-git/issues/152/cant-pull-single-branch-using-hg-b) preventing me from pulling.

**Comment by jaraco** [comment]
Oh, awesome! Thanks!

**Pull request merged**
