### PR TITLE
tests: fix_test_build_deps_on_distutils

### PR DESCRIPTION
**Pull request by benoit-pierre**
Ignore distutils' warning: `Unknown distribution option: 'python_requires'`.

### CODE REVIEW

**Comment by venthur** [comment]
Thanks for the quick fix! I'll refresh #1761 asap.

**Comment by benoit-pierre** [comment]
*sigh* still broken on Windows...

**Comment by benoit-pierre** [comment]
@venthur: once it's merged, you'll just have to close and re-open the PR, no need to rebase.

**Comment by venthur** [comment]
I usually just refresh the branch with the latest commits from master.

**Comment by benoit-pierre** [comment]
You don't have to, closing and re-opening will re-trigger a test run with the result of merging to master.

**Comment by benoit-pierre** [comment]
And now there's **another** issue on Windows... ;( And I notice there's an `UNKNOWN==0.0.0` package in the tox environment...

**Comment by benoit-pierre** [comment]
So why did `more-itertools==7.0.0` get installed for the Window Python 2.7 job when it's `python_requires` is `>=3.4`?

**Comment by venthur** [comment]
Maybe it is a good idea to pin all the versions in `tests/requirements.txt` and update them once in a while as a conscious decision?

**Comment by benoit-pierre** [comment]
Yes, that's what @pganssle [suggested](https://github.com/pypa/setuptools/pull/1761#issuecomment-492234274), that still does not explain what's happening.

**Comment by venthur** [comment]
Well, you never really know what get's installed as a dependencies dependency when you don't pin the versions.
In order to investigate what's going on, you could temporarily install and run [pipdeptree](https://pypi.org/project/pipdeptree/) in order to see pulled in what.

**Comment by benoit-pierre** [comment]
The problem was the tox virtual environment was using an old version of pip (not sure which one, that's a really important information, but not part of tox's logs). Unfortunately, there's also no way to pin it... Updating virtualenv seems to have fixed it.

**Pull request merged**
