### PR TITLE
Rename find_namepaces_ns to find_namespace_packages

### LINKED ISSUE #1421: Refactor rename find_packages_ns to find_namespace_packages
As @pganssle mentioned in #1420, the export `find_packages_ns` is rather obscure and should be renamed to `find_namespace_packages`. This also goes in line with the new `find_namespace:` directive when using `setup.cfg` that was introduced by the PR #1420 as requested by #1419.

### PR DESCRIPTION
**Pull request by silkentrance**
## Summary of changes

Rename find_namepaces_ns to find_namespace_packages

Closes #1421

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by silkentrance** [comment]
Please note that this branch is based on #1420, so the latter must be merged first.

**Comment by silkentrance** [comment]
As for the changelog change entry, do we keep the one for #1312?

**Comment by pganssle** [comment]
@silkentrance I think we can just update the 1312 one so that it says `find_namespace_packages` instead of `find_packages_ns`. Since 1312 hasn't been released yet it doesn't make much sense to include a changelog that says, "We were going to do X but instead we did Y".

**Comment by silkentrance** [comment]
The build for Python3.4 is failing due to missing dependencies?!

**Comment by pganssle** [comment]
I can't get this failure to happen again locally, but restarting it didn't fix it. I cleared the PR cache and nothing.

I think if you revert the changes that import things from `setuptools.tests` it should fix it?

**Comment by silkentrance** [comment]
@pganssle Using relative imports did the trick. Thanks for the advise.

**Comment by pganssle** [comment]
Thanks again for your hard work on this @silkentrance.

**Pull request merged**
