### PR TITLE
WIP: Debugging branch for pip upgrades in test_virtualenv

### PR DESCRIPTION
**Pull request by pganssle**
Rather than spamming and force-pushing to #1659, I've created this new PR for debugging the issue with `pip install -U pip` on appveyor.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
It's the usual Windows issue, the code need to be changed to use `python -m pip`, otherwise pip's executable cannot be upgraded (because it's in use).

**Comment by pganssle** [comment]
@benoit-pierre Ah, I didn't realize this, OK.

**Comment by pganssle** [comment]
@benoit-pierre Do you want to push an update to #1659, otherwise I can.

**Comment by benoit-pierre** [comment]
I've just pushed one.

**Pull request closed without merging**
