### PR TITLE
All extra names must be converted to lower case. use pkg_resources.sa…

### PR DESCRIPTION
**Pull request by GabrielC101**
Fixes  pypa/pip#4617. Supposedly.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
This patch is mangling the environment markers.

**Comment by GabrielC101** [comment]
I'll have to come back to this later.

**Comment by GabrielC101** [comment]
Note: setuptools makes the extras safe when parsing the Requirement object args.  https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L3006

**Comment by GabrielC101** [comment]
setuptools.pkg_resources.evaluate_marker claims to determine if a string is a valid marker. Yet the string ':python_version=="2.7"' is considered invalid. 

Is evaluate_marker reliable? Ultimately the decision is made by the pyparsing grammer. I'm having difficulty deciphering it.

**Comment by benoit-pierre** [comment]
`':python_version=="2.7"'` is not a valid marker, `'python_version=="2.7"'` is.

**Comment by GabrielC101** [comment]
This commit uses the same process used in _check_extra to separate an extra name from the environment markers. It then uses the safe_extras method to convert the extra name before recreating the section.

This ensures setuptools views extra names as case insensitive.

**Pull request closed without merging**
