### PR TITLE
Prefer native strings on Python 2 when reading config files.

### LINKED ISSUE #1653: TypeError: 'output_dir' must be a string or None since setuptools 40.7.0
We have a [tricky regression](https://bugs.gentoo.org/676608) in Gentoo with setuptools release 40.7.0. This affects many (all?) packages that involve `build_ext`. These errors aren't present in 40.6.3. I think I managed to have reproducible steps:

```
git clone https://github.com/python-pillow/Pillow.git
cd Pillow
virtualenv -p python2 env
. env/bin/activate
pip install -U setuptools
echo -e "[build]\nbuild-base = /tmp/foo" >> setup.cfg
mkdir /tmp/foo
python setup.py build
[...]
Traceback (most recent call last):
  File "setup.py", line 793, in <module>
    zip_safe=not (debug_build() or PLATFORM_MINGW), )
  File "/home/vdupras/src/Pillow/env/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 695, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 499, in build_extension
    depends=ext.depends)
  File "/home/vdupras/src/Pillow/mp_compile.py", line 40, in _mp_compile
    output_dir, macros, include_dirs, sources, depends, extra_postargs)
  File "/usr/lib64/python2.7/distutils/ccompiler.py", line 329, in _setup_compile
    raise TypeError, "'output_dir' must be a string or None"
TypeError: 'output_dir' must be a string or None
```

Can you reproduce on your side?

It the fix isn't obvious, I can try myself on a PR soon.

(by the way, this is due to distutils's `isinstance()` call being made on `str` rather than `basestring` and only happens under py2. `output_dir` is unicode when it should be `str`)

### PR DESCRIPTION
**Pull request by jaraco**
## Summary of changes

Closes #1653

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in changelog.d.

### CODE REVIEW

**Comment by jaraco** [comment]
My intention is to release this as a commit against v40.7.0 as v40.7.1 without the other commits currently on master.

**Comment by ofek** [comment]
Will the release happen tonight?

**Comment by jaraco** [comment]
40.7.1 should be [releasing here momentarily](https://travis-ci.org/pypa/setuptools/builds/485667664)

**Comment by ofek** [comment]
Many thanks!

**Pull request merged**
