### PR TITLE
Exclude .pyc in sdist output

### LINKED ISSUE #1414: setup.py sdist produces a tarball containing .pyc files, breaking stdeb
`.pyc` files are compiled Python bytecode binaries, are specific to the particular version of Python being installed, and really do not belong in a source package as there's no guarantee that the package will be compiled on the *same* version of Python.

The following steps reliably results in a source tarball containing `.pyc` files.

<details>

```
$ git clone --depth=1 https://github.com/pypa/setuptools.git
Cloning into 'setuptools'...
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 202 (delta 11), reused 57 (delta 3), pack-reused 0
Receiving objects: 100% (202/202), 586.02 KiB | 1.33 MiB/s, done.
Resolving deltas: 100% (11/11), done.
$ cd setuptools
$ git log
commit 54ce65990c26ff68750ae682b6bacd5eed7d56ba
Author: Paul Ganssle <pganssle@users.noreply.github.com>
Date:   Mon Jul 9 09:24:10 2018 -0400

    Merge pull request #1410 from di/deprecate-upload-and-register
    
    Deprecate upload and register commands
$ python2 bootstrap.py 
adding minimal entry_points
Regenerating egg_info
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
...and again.
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
$ python2 setup.py sdist --formats=gztar
running sdist
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
running check
creating setuptools-40.0.0.post20180710
creating setuptools-40.0.0.post20180710/.github
creating setuptools-40.0.0.post20180710/changelog.d
creating setuptools-40.0.0.post20180710/docs
creating setuptools-40.0.0.post20180710/docs/_templates
creating setuptools-40.0.0.post20180710/docs/_theme
creating setuptools-40.0.0.post20180710/docs/_theme/nature
creating setuptools-40.0.0.post20180710/docs/_theme/nature/static
creating setuptools-40.0.0.post20180710/pkg_resources
creating setuptools-40.0.0.post20180710/pkg_resources/_vendor
creating setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
creating setuptools-40.0.0.post20180710/pkg_resources/extern
creating setuptools-40.0.0.post20180710/pkg_resources/tests
creating setuptools-40.0.0.post20180710/setuptools
creating setuptools-40.0.0.post20180710/setuptools.egg-info
creating setuptools-40.0.0.post20180710/setuptools/_vendor
creating setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
creating setuptools-40.0.0.post20180710/setuptools/command
creating setuptools-40.0.0.post20180710/setuptools/extern
creating setuptools-40.0.0.post20180710/setuptools/tests
creating setuptools-40.0.0.post20180710/setuptools/tests/indexes
creating setuptools-40.0.0.post20180710/setuptools/tests/indexes/test_links_priority
creating setuptools-40.0.0.post20180710/setuptools/tests/indexes/test_links_priority/simple
creating setuptools-40.0.0.post20180710/setuptools/tests/indexes/test_links_priority/simple/foobar
creating setuptools-40.0.0.post20180710/tests
copying files to setuptools-40.0.0.post20180710...
copying .codecov.yml -> setuptools-40.0.0.post20180710
copying .gitignore -> setuptools-40.0.0.post20180710
copying .travis.yml -> setuptools-40.0.0.post20180710
copying CHANGES.rst -> setuptools-40.0.0.post20180710
copying LICENSE -> setuptools-40.0.0.post20180710
copying MANIFEST.in -> setuptools-40.0.0.post20180710
copying README.rst -> setuptools-40.0.0.post20180710
copying appveyor.yml -> setuptools-40.0.0.post20180710
copying bootstrap.py -> setuptools-40.0.0.post20180710
copying conftest.py -> setuptools-40.0.0.post20180710
copying easy_install.py -> setuptools-40.0.0.post20180710
copying launcher.c -> setuptools-40.0.0.post20180710
copying msvc-build-launcher.cmd -> setuptools-40.0.0.post20180710
copying netlify.toml -> setuptools-40.0.0.post20180710
copying pavement.py -> setuptools-40.0.0.post20180710
copying pyproject.toml -> setuptools-40.0.0.post20180710
copying pytest.ini -> setuptools-40.0.0.post20180710
copying setup.cfg -> setuptools-40.0.0.post20180710
copying setup.py -> setuptools-40.0.0.post20180710
copying towncrier_template.rst -> setuptools-40.0.0.post20180710
copying tox.ini -> setuptools-40.0.0.post20180710
copying .github/pull_request_template.md -> setuptools-40.0.0.post20180710/.github
copying changelog.d/1410.change.rst -> setuptools-40.0.0.post20180710/changelog.d
copying docs/Makefile -> setuptools-40.0.0.post20180710/docs
copying docs/conf.py -> setuptools-40.0.0.post20180710/docs
copying docs/developer-guide.txt -> setuptools-40.0.0.post20180710/docs
copying docs/development.txt -> setuptools-40.0.0.post20180710/docs
copying docs/easy_install.txt -> setuptools-40.0.0.post20180710/docs
copying docs/formats.txt -> setuptools-40.0.0.post20180710/docs
copying docs/history.txt -> setuptools-40.0.0.post20180710/docs
copying docs/index.txt -> setuptools-40.0.0.post20180710/docs
copying docs/pkg_resources.txt -> setuptools-40.0.0.post20180710/docs
copying docs/python3.txt -> setuptools-40.0.0.post20180710/docs
copying docs/releases.txt -> setuptools-40.0.0.post20180710/docs
copying docs/requirements.txt -> setuptools-40.0.0.post20180710/docs
copying docs/roadmap.txt -> setuptools-40.0.0.post20180710/docs
copying docs/setuptools.txt -> setuptools-40.0.0.post20180710/docs
copying docs/_templates/indexsidebar.html -> setuptools-40.0.0.post20180710/docs/_templates
copying docs/_theme/nature/theme.conf -> setuptools-40.0.0.post20180710/docs/_theme/nature
copying docs/_theme/nature/static/nature.css_t -> setuptools-40.0.0.post20180710/docs/_theme/nature/static
copying docs/_theme/nature/static/pygments.css -> setuptools-40.0.0.post20180710/docs/_theme/nature/static
copying pkg_resources/__init__.py -> setuptools-40.0.0.post20180710/pkg_resources
copying pkg_resources/api_tests.txt -> setuptools-40.0.0.post20180710/pkg_resources
copying pkg_resources/py31compat.py -> setuptools-40.0.0.post20180710/pkg_resources
copying pkg_resources/_vendor/__init__.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor
copying pkg_resources/_vendor/appdirs.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor
copying pkg_resources/_vendor/pyparsing.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor
copying pkg_resources/_vendor/six.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor
copying pkg_resources/_vendor/vendored.txt -> setuptools-40.0.0.post20180710/pkg_resources/_vendor
copying pkg_resources/_vendor/packaging/__about__.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/__init__.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_compat.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/_structures.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/markers.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/requirements.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/specifiers.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/utils.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/_vendor/packaging/version.py -> setuptools-40.0.0.post20180710/pkg_resources/_vendor/packaging
copying pkg_resources/extern/__init__.py -> setuptools-40.0.0.post20180710/pkg_resources/extern
copying pkg_resources/tests/__init__.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying pkg_resources/tests/test_find_distributions.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying pkg_resources/tests/test_markers.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying pkg_resources/tests/test_pkg_resources.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying pkg_resources/tests/test_resources.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying pkg_resources/tests/test_working_set.py -> setuptools-40.0.0.post20180710/pkg_resources/tests
copying setuptools/__init__.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/archive_util.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/build_meta.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/cli-32.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/cli-64.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/cli.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/config.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/dep_util.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/depends.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/dist.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/extension.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/glibc.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/glob.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/gui-32.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/gui-64.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/gui.exe -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/launch.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/lib2to3_ex.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/monkey.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/msvc.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/namespaces.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/package_index.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/pep425tags.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/py27compat.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/py31compat.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/py33compat.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/py36compat.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/sandbox.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/script (dev).tmpl -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/script.tmpl -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/site-patch.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/ssl_support.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/unicode_utils.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/version.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/wheel.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools/windows_support.py -> setuptools-40.0.0.post20180710/setuptools
copying setuptools.egg-info/PKG-INFO -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/SOURCES.txt -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/dependency_links.txt -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/entry_points.txt -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/requires.txt -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/top_level.txt -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools.egg-info/zip-safe -> setuptools-40.0.0.post20180710/setuptools.egg-info
copying setuptools/_vendor/__init__.py -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/__init__.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/pyparsing.py -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/six.py -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/six.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/vendored.txt -> setuptools-40.0.0.post20180710/setuptools/_vendor
copying setuptools/_vendor/packaging/__about__.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/__about__.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/__init__.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/__init__.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_compat.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_compat.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_structures.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/_structures.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/markers.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/requirements.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/specifiers.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/specifiers.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/utils.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/version.py -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/_vendor/packaging/version.pyc -> setuptools-40.0.0.post20180710/setuptools/_vendor/packaging
copying setuptools/command/__init__.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/alias.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/bdist_egg.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/bdist_rpm.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/bdist_wininst.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/build_clib.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/build_ext.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/build_py.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/develop.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/dist_info.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/easy_install.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/egg_info.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/install.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/install_egg_info.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/install_lib.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/install_scripts.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/launcher manifest.xml -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/py36compat.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/register.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/rotate.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/saveopts.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/sdist.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/setopt.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/test.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/upload.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/command/upload_docs.py -> setuptools-40.0.0.post20180710/setuptools/command
copying setuptools/extern/__init__.py -> setuptools-40.0.0.post20180710/setuptools/extern
copying setuptools/tests/__init__.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/contexts.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/environment.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/files.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/fixtures.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/mod_with_constant.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/namespaces.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/script-with-bom.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/server.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_archive_util.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_bdist_egg.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_build_clib.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_build_ext.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_build_meta.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_build_py.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_config.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_dep_util.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_depends.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_develop.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_dist.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_dist_info.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_easy_install.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_egg_info.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_find_packages.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_glibc.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_install_scripts.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_integration.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_manifest.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_msvc.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_namespaces.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_packageindex.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_pep425tags.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_register.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_sandbox.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_sdist.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_setuptools.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_test.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_unicode_utils.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_upload.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_upload_docs.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_virtualenv.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_wheel.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/test_windows_wrappers.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/text.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/textwrap.py -> setuptools-40.0.0.post20180710/setuptools/tests
copying setuptools/tests/indexes/test_links_priority/external.html -> setuptools-40.0.0.post20180710/setuptools/tests/indexes/test_links_priority
copying setuptools/tests/indexes/test_links_priority/simple/foobar/index.html -> setuptools-40.0.0.post20180710/setuptools/tests/indexes/test_links_priority/simple/foobar
copying tests/manual_test.py -> setuptools-40.0.0.post20180710/tests
copying tests/requirements.txt -> setuptools-40.0.0.post20180710/tests
Writing setuptools-40.0.0.post20180710/setup.cfg
creating dist
Creating tar archive
removing 'setuptools-40.0.0.post20180710' (and everything under it)
$ tar -tzf dist/setuptools-40.0.0.post20180710.tar.gz | grep pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/__about__.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/__init__.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/_compat.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/_structures.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/specifiers.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/packaging/version.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/__init__.pyc
setuptools-40.0.0.post20180710/setuptools/_vendor/six.pyc
```
</details>

**Edit from @pganssle**: Moved the details into a `<details>` tag so the ticket wouldn't be quite so long.

### PR DESCRIPTION
**Pull request by gokcennurlu**
## Summary of changes

This restricts the `recursive-include setuptools/_vendor` to contain only .py and .txt files.

Closes #1414

### Pull Request Checklist
- ~Changes have tests~
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by benoit-pierre** [comment]
The issue is really with the `recursive-include setuptools/_vendor *` rule in `MANIFEST.in`, so you could use a stricter exclusion: `recursive-exclude setuptools/_vendor *.pyc`.

**Comment by benoit-pierre** [comment]
Or alternatively, fix the original `_vendor` rule to be less inclusive.

**Comment by gokcennurlu** [comment]
@benoit-pierre Thank you, I will look into fixing it now!

I spent some time to understand the codepath that leads to manifest & sources.txt generation and tried to figure out if this is just a `MANIFEST.in` fix or a behaviour change is required in setuptools itself. AFAIK, we are just removing .pyc files __in this project__, right? In that case, we shouldn't really need a test here.

**Comment by benoit-pierre** [comment]
I agree that no test is needed.

**Comment by pganssle** [comment]
We probably don't need a test, though I think to verify the correctness, we should build the `sdist` twice, so if we assume we have two tarballs, `setuptools_before.tar.gz` and `setuptools_after.tar.gz`, then:

```
tar -tf setuptools_before.tar.gz > s_before.txt
tar -tf setuptools_after.tar.gz > s_after.txt
diff s_before.txt s_after.txt
```

The result of this should contain *only* `pyc` files removed, and:

```
tar -tf setuptools_after.tar.gz | grep .pyc
```

Should return nothing.

**Comment by pganssle** [comment]
Actually, maybe we should add a test for this, but only in the release script - if the release script could hard-fail if the sdist contains `*.pyc` files, that's probably enough to prevent us from making invalid releases.

**Comment by gokcennurlu** [comment]
@pganssle I can verify that the fix works
<details>

```bash
## Before
$ git clone git@github.com:pypa/setuptools.git before --depth 1 && cd before
$ python2.7 bootstrap.py
adding minimal entry_points
Regenerating egg_info
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
...and again.
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
$ python2.7 setup.py sdist -d dist-before --formats=tar
...

## After
$ git clone git@github.com:pypa/setuptools.git after --depth 1 && cd after
# Assuming that you fetched the PR ref
$ git checkout f25c12c2f60fe524a92282337c999b64d2c8ba91
$ python2.7 bootstrap.py
adding minimal entry_points
Regenerating egg_info
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
writing manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
...and again.
running egg_info
writing requirements to setuptools.egg-info/requires.txt
writing setuptools.egg-info/PKG-INFO
writing top-level names to setuptools.egg-info/top_level.txt
writing dependency_links to setuptools.egg-info/dependency_links.txt
writing entry points to setuptools.egg-info/entry_points.txt
reading manifest file 'setuptools.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'setuptools.egg-info/SOURCES.txt'
$ python2.7 setup.py sdist -d dist-after --formats=tar
$ cd ..

## Verifying
$ tar -tf before/dist-before/setuptools-40.5.0.post20181027.tar > before.txt
$ tar -tf after/dist-after/setuptools-40.5.0.post20181027.tar > after.txt
$ diff before.txt after.txt
```
```diff
72d71
< setuptools-40.5.0.post20181027/setuptools/_vendor/__init__.pyc
75d73
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/__about__.pyc
77d74
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/__init__.pyc
79d75
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/_compat.pyc
81d76
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/_structures.pyc
85d79
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/specifiers.pyc
88d81
< setuptools-40.5.0.post20181027/setuptools/_vendor/packaging/version.pyc
91d83
< setuptools-40.5.0.post20181027/setuptools/_vendor/six.pyc

```
</details>

I don't know much about the release process though. Where exactly can we add such checks?

**Comment by gokcennurlu** [comment]
Travis's PyPI plugin already calls `sdist` and I didn't want to call it manually and possibly intervene what's going to do. Yet, all those commands work based on .egg-info folder's content, I think something like this in travis file would work?
```yaml
before_deploy:
  - python bootstrap.py
  - ! grep pyc setuptools.egg-info/SOURCES.txt
``` 
What do you think? It'd be hard to test this check before actually releasing something, though :D

**Comment by pganssle** [comment]
@gokcennurlu I think I'm fine with that, it seems like it does the right thing.  If run the commands that the deploy script does locally and it fails on master but succeeds in this PR, I trust it.

**Comment by gokcennurlu** [comment]
`run_egg_info()` in `bootstrap.py` seems to be the reason why pycs are there - to bootstrap and run egg_info on itself. I guess we'd not see those pyc files if we used an existing setuptools to run setup.py commands.

**Comment by pganssle** [comment]
Good thing we added the `! grep pyc ...` line, since that failed when making the 40.6.0 release.

**Pull request merged**
