### PR TITLE
Fixes for python3.10

### PR DESCRIPTION
**Pull request by asottile**
## Summary of changes

found using [asottile/python3.10](https://github.com/asottile/python3.10)

### Pull Request Checklist
- [X] Changes have tests -- 17 tests failed prior to this change
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by asottile** [comment]
@pganssle would appreciate a review <3

**Comment by pganssle** [comment]
I think it might be good to pull this from a centralized place rather than repeating the same formatting idiom in a bunch of places.

**Comment by asottile** [comment]
sounds good -- do you have a recommended place to put this little helper "constant"?

**Comment by asottile** [comment]
@pganssle ping! should I put these in some sort of `_compat` module?

**Comment by pganssle** [comment]
@asottile I dunno if `_compat` is right, it's more like `_environment` or `_platform` or something.

The one in `setup.py` can stay as it is, though.

@jaraco Do you have any suggestions, code-organization-wise?

**Comment by jaraco** [comment]
Honestly, I struggle with a good place to put this logic, because the usage appears in

- setuptools/* (4)
- pkg_resources/* (including doctests) (3)
- setup.py (1)

There's just no good place to this indication. Here's what I suggest - let's wait for this idiom (or the resulting value) to appear in `packaging` (on which both pkg_resources and setuptools both depend) and then rely on it from there (except maybe for setup.py).

And in the meantime, let's accept it as proposed.

**Pull request merged**
