### PR TITLE
Remove spurious executable permissions

### PR DESCRIPTION
**Pull request by hroncok**
## Summary of changes

Remove spurious executable permissions from files that don't need them.

### Pull Request Checklist
- [ ] Changes have tests (not really, but I really doubt the usefulness) 
- [x] News fragment added in changelog.d.

### CODE REVIEW

**Comment by jaraco** [comment]
This change seems useful. Should we give the same treatment to the other files in the root of the project?

**Comment by jaraco** [comment]
And probably all files in the project that don't need to be executable. I see executable bits on, for example, setuptools/namespaces.py.

**Comment by hroncok** [comment]
launcher.c, pytest.ini, ok, I'll try to get them all.

**Comment by hroncok** [comment]
Amended.

**Comment by jaraco** [comment]
Excellent. Thanks!

**Pull request merged**
