### PR TITLE
Fix "Microsoft Visual C++ Build Tools" link

### LINKED ISSUE #1394: URL to Visual Studio download is dead
The url in this message is no longer active:

https://github.com/pypa/setuptools/blob/818ba40529993d8f318fe282bdb8420455dbf926/setuptools/msvc.py#L232-L236

The current best URL is `https://visualstudio.microsoft.com/downloads/` and the title is "Build Tools for Visual Studio"

### PR DESCRIPTION
**Pull request by JGoutin**
## Summary of changes

Fix Microsoft Visual C++ Build Tools dead link.

Closes #1394

### Pull Request Checklist
- [ ] Changes have tests: **Only change link in string.**
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by pganssle** [comment]
According to @zooba in #1394:

> The current best URL is https://visualstudio.microsoft.com/downloads/ and the title is "Build Tools for Visual Studio"

Given that Steve works for Microsoft I believe him - plus his link is https.

**Comment by pganssle** [comment]
I'm tempted to add a `# pragma: nocover` comment to the version switch, but I think it doesn't really make sense to do so, so we can just merge even with 0% diff coverage for now.

**Comment by JGoutin** [comment]
The link I set in PR is in fact a redirection to the like you quoted. It look to work also in HTTPS. So I replaced the link.

**Comment by JGoutin** [comment]
Normalized formatting.

**Pull request merged**
