### PR TITLE
When reading config files, require them to be encoded with UTF-8.

### LINKED ISSUE #1702: setup.cfg should standardize on UTF-8 for encoding
In jaraco/configparser#34, I learned that although setuptools v40.7.0 presumably added support for non-ASCII, there are still environments where loading non-ASCII is failing.

```
configparser # easy_install --version
setuptools 40.8.0 from c:\python37\lib\site-packages (Python 3.7)
configparser 3.7.2 # python setup.py egg_info
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    package_dir={'': 'src'},  
  File "C:\Python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
    _install_setup_requires(attrs)  
  File "C:\Python37\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "C:\Python37\lib\site-packages\setuptools\dist.py", line 702, in parse_config_files
    self._parse_config_files(filenames=filenames)
  File "C:\Python37\lib\site-packages\setuptools\dist.py", line 599, in _parse_config_files
    (parser.read_file if six.PY3 else parser.readfp)(reader)
  File "C:\Python37\lib\configparser.py", line 717, in read_file
    self._read(f, source)
  File "C:\Python37\lib\configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "C:\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 103: character maps to <undefined>
```

### PR DESCRIPTION
**Pull request by jaraco**
Closes #1702

### Pull Request Checklist
- [X] Changes have tests
- [x] News fragment added in changelog.d. See [documentation](http://setuptools.readthedocs.io/en/latest/developer-guide.html#making-a-pull-request) for details

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Shouldn't the `setuptools.unicode_utils.detect_encoding` helper be removed?

**Comment by jaraco** [comment]
@pganssle I'd like to merge and release this today, so if you have any reservations, please let me know.

**Comment by pganssle** [comment]
I don't have a major problem with the idea. My over-cautious instinct is to deprecate first, but this is such an easy thing to fix if it breaks something that maybe it's not worth it?

(Famous last words)

**Comment by jaraco** [comment]
Good point. Here's my thinking: because the behavior was only recently released (January), probably not many project depend on the behavior or those that do are likely already cutting-edge enough to rely on this latest release. Moreover, if we find that releasing this does cause problems, I'll be on standby to release a bugfix release to add backward compatibility if needed (so only a small window of the problemmatic release).

**Comment by pganssle** [comment]
Oh if you are reversing a recently introduced behavior then I think it's even less likely to cause problems, I say go for it.

**Comment by jaraco** [comment]
Thanks both. In the interest of progress, I'm going to move forward with this, but don't hesitate to raise other concerns or thoughts.

**Pull request merged**
