### PR TITLE
Added some entry points required for bootstrapping from source.

### LINKED ISSUE #2550: Clarity on installation from source
Setuptools exists at a unique place in the Python ecosystem, and although this project aims to be a distributed third-party package like any other, because it is required to build many of the packages in the ecosystem, it has unique bootstrapping challenges, including:

- Attempt to unvendor dependencies (#1981).
- Attempt to rely on PEP 517 for bootstrapping (#2543).

I'd like to put together a story (documentation) about how to bootstrap a Python system to include Setuptools from source, including some integration tests that continuously validate these expectations and the associated constraints so that upstream platforms like Fedora and Debian can have a reliable means to supply Setuptools (only) when needed.

### PR DESCRIPTION
**Pull request by KOLANICH**
## Summary of changes

<details>
<summary>Excerpt from a DOCKERFILE to bootstrap python packaging</summary>

```
	git clone --depth=50 https://github.com/pypa/setuptools.git;\
	git clone --depth=50 https://github.com/pypa/setuptools_scm.git;\
	git clone --depth=50 https://github.com/pypa/pip.git;\
	git clone --depth=50 https://github.com/pypa/wheel.git;\
	export SUDO=;\
	cd ./wheel;\
	python3 -c "import re;from pathlib import Path;f=Path('setup.cfg');f.write_text(re.subn('^setup_requires.+$', '', f.read_text(), flags=re.MULTILINE)[0])";\
	PYTHONPATH=../setuptools:./src $SUDO python3 ./setup.py install;\
	cd ../setuptools;\
	python3 ./setup.py install;\
	python3 ./setup.py bdist_wheel;\
	PYTHONPATH=../pip/src $SUDO python3 -m pip install --upgrade --force-reinstall ./dist/*.whl;\
	cd ../wheel;\
	PYTHONPATH=../setuptools python3 ./setup.py bdist_wheel;\
	PYTHONPATH=../pip/src $SUDO python3 -m pip install --upgrade --force-reinstall ./dist/*.whl;\
	cd ../pip;\
	python3 ./setup.py bdist_wheel;\
	PYTHONPATH=./src $SUDO python3 -m pip install --upgrade --force-reinstall ./dist/*.whl;\
	cd ../setuptools_scm;\
	python3 ./setup.py bdist_wheel;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	cd ..;\
	rm -rf ./setuptools ./pip ./wheel;\
	git clone --depth=50 https://github.com/uiri/toml.git;\
	cd ./toml;\
	python3 ./setup.py bdist_wheel;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	cd ..;\
	echo todo: $SUDO pip3 install --upgrade --force-reinstall ./setuptools_scm/dist/*.whl[toml];\
	rm -rf ./toml ./setuptools_scm;\
	\
	git clone --depth=50 https://github.com/pyparsing/pyparsing.git;\
	cd ./pyparsing;\
	python3 ./setup.py bdist_wheel;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	cd ..;\
	rm -rf ./pyparsing;\
	\
	git clone --depth=50 https://github.com/takluyver/flit.git;\
	cd flit/flit_core;\
	python3 -c "from flit_core import build_thyself;build_thyself.build_wheel('./')";\
	$SUDO pip3 install --upgrade ./*.whl;\
	cd ../..;\
	rm -rf ./flit;\
	\
	git clone --depth=50 https://github.com/pypa/packaging.git;\
	git clone --depth=50 https://github.com/pypa/pep517.git;\
	git clone --depth=50 https://github.com/pypa/build.git;\
	\
	cd pep517;\
	PYTHONPATH=../build/src:../packaging python3 -m build -xnw .;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	\
	cd ../packaging;\
	PYTHONPATH=../build/src python3 -m build -xnw .;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	cd ..;\
	rm -rf ./packaging;\
	\
	cd ./build;\
	PYTHONPATH=./src python3 -m build -xnw .;\
	$SUDO pip3 install --upgrade ./dist/*.whl;\
	cd ..;\
	rm -rf ./pep517 ./build ./packaging;\
```

</details>

<details>
<summary>Log</summary>

1. First tried `bdist_wheel` for setuptools. Damn, it tries to install `wheel` with `pip` because it is a build dep. Trying to make use of non-installed `wheel` is unsuccesful.

2. OK, tried to build `wheel` with non-installed `setuptools` + non-installed `wheel`. No success. `wheel` needs installed `wheel`. OK, `wheel` uses `setup.cfg`, it's fairly easy to remove `install_requires`. `python3 -c import re;from pathlib import Path;f=Path('setup.cfg');f.write_text(re.subn('^setup_requires.+$', '', f.read_text(), flags=re.MULTILINE)[0])` Then `python ./setup.py install` succeeds (how? why?). `bdist_wheel` though doesn't IDK why, seems like just `install` doesn't register entry points.

3. OK, added an entry point for `bdist_wheel`. Damn, `error: cannot copy tree 'build/scripts-3.9': not a directory`. Trying to solve by installing setuptools.

4. trying to `python3 ./setup.py install` in setuptools dir. `error: invalid command 'easy_install'`. Why??? No entry point. Created a patch with them. Then install succeeds. 

5. then we can build a wheel for setuptools and install it

6. then we can go to `wheel` dir, set `PYTHONPATH` to `setuptools` dir to get a get the ehtry points for `bdist_wheel`, build a wheel for it and install.

</details>

Closes #2550

### Pull Request Checklist
- [ ] Changes have tests - not needed
- [ ] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.readthedocs.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by KOLANICH** [comment]
@jaraco, is there anything that preventsit from being merged?

**Comment by benoit-pierre** [comment]
Tests?

**Comment by benoit-pierre** [comment]
And why do you need that? Why not run `python setup.py egg_info` in the setuptools directory first?

**Comment by KOLANICH** [comment]
Will try that, though it likely won't work. We need bdist_wheel workable to install `setuptools` properly (`setup.py install` doesn't set needed entry points), so I ended-up with the following dockerfile: https://gitlab.com/KOLANICH-subgroups/docker-images/fixed_python/raw/master/Dockerfile

>Tests?

I feel like the only proper way to test it is to run the part of the mentioned Dockerfile in a clean environment.

**Comment by webknjaz** [comment]
(closed/reopened to trigger GH events/CI stuff)

**Comment by jaraco** [comment]
I'm closing this (without prejudice). Feel free to comment and we can re-open. Or re-submit when ready. Thanks.

**Comment by KOLANICH** [comment]
There will be no tests and likely no reopening, since it seems it is not needed by the project.  If it was, it'd have been already implemented and this PR wouldn't have been existing at all. 
It feels like everyone except me is OK with depending on prebuilt packages from pip. For me it is simpler to modify my CI pipelines so the sources of `setuptools` are patched, than to implement tests making no sense (that stuff should "tested" every time setuptools package is built) in order to meet formal requirements for accepting of the patch into upstream. So be it.

**Comment by jaraco** [comment]
The question I'd like to see answered is this one:

> And why do you need that? Why not run `python setup.py egg_info` in the setuptools directory first?

If you add that between steps 3 and 4, does that work?

**Comment by KOLANICH** [comment]
@benoit-pierre, @jaraco, thank you. It works for GitLab CI pipeline: https://gitlab.com/KOLANICH-subgroups/docker-images/fixed_python/-/jobs/1648667066

But not for GitHub Actions one: https://github.com/KOLANICH-libs/RichConsole.py/runs/3797498484

>`AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'`

**Comment by jaraco** [comment]
The traceback in that run is thus:

```
Traceback (most recent call last):
    File "./setup.py", line 87, in <module>
      dist = setuptools.setup(**setup_params)
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/setuptools/dist.py", line 453, in __init__
      _Distribution.__init__(
    File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/setuptools/dist.py", line 830, in finalize_options
      for ep in sorted(loaded, key=by_order):
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/setuptools/dist.py", line 829, in <lambda>
      loaded = map(lambda e: e.load(), filtered)
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/pkg_resources/__init__.py", line 2450, in load
      return self.resolve()
    File "/home/runner/work/RichConsole.py/RichConsole.py/setuptools/pkg_resources/__init__.py", line 2460, in resolve
      raise ImportError(str(exc)) from exc
  ImportError: type object 'Distribution' has no attribute '_finalize_feature_opts'
```

You'll notice that `_finalize_feature_opts` is an old entry point, probably present due to an existing installation of setuptools. Se here's what I think is happening:

1. An old version of Setuptools with that entrypoint is still present.
2. When `setuptools.dist.Distribution.finalize_options` is called, it enumerates all of the `setuptools.finalize_distribution_options` entry points and calls each.
3. Because the old setuptools declares a `setuptools.dist.Distribution._finalize_feature_opts` as one of those entry points, Setuptools attempts to load it.
4. The local copy of setuptools is newer and doesn't have that entry point.
5. Because the local `setuptools` Python package is ahead on the Python path, an error occurs trying to load that entry point.

You have a few options here. You could manually uninstall setuptools from the system site packages. Or you could try running with `-S` to avoid the implied `import site` to exclude system site packages. Or you could get a CI image that includes a newer version of Setuptools without that metadata.

Regardless, I don't think adding entry points to the bootstrapping metadata would help here.

I recommend to file a new issue to track the missed expectation if there still is one.

**Comment by KOLANICH** [comment]
Yeah, I have already solved this issue by 

```bash
sudo rm -rf /usr/lib/python3/dist-packages/setuptools;
sudo rm -rf /usr/lib/python3/dist-packages/setuptools-*.egg-info;
```

**Pull request closed without merging**
