### PR TITLE
Update deprecation warning

### PR DESCRIPTION
**Pull request by martonp**
## Summary of changes
Added custom deprecation warning classes because DeprecationWarning is not visible unless the user opts in. 

Closes Issue #159

### CODE REVIEW

**Comment by brainwane** [comment]
Thanks for writing a descriptive commit message. [Here's a guide to help you write commit messages](https://zulip.readthedocs.io/en/latest/version-control.html#commit-messages) that are more consistent with our style, which makes it easier for us in the future -- when someone's trying to solve a new problem, if commit messages are all in the same format, it's easier to skim them in logs and quickly understand what's happening.

[Here are some tips on tidying your commit history, including changing your commit messages.](https://zulip.readthedocs.io/en/latest/git-guide.html#examine-and-tidy-your-commit-history) And when you update your code or your commit message, you can [update your pull request](https://zulip.readthedocs.io/en/latest/git-guide.html#update-a-pull-request) and the changes will appear here. :)

**Comment by brainwane** [comment]
Also: https://blog.jaraco.com/how-to-write-perfect-pull-request/

**Comment by brainwane** [comment]
Thank you for the PR! I'll now leave substantive comment to the setuptools maintainers. :-)

**Comment by martonp** [comment]
Opening another one.

**Pull request closed without merging**
