### PR TITLE
Update keywords note on editable installs

### PR DESCRIPTION
**Pull request by evamaxfield**
## Summary of changes

Updates the keywords note about editable installations requiring a minimal `setup.py` file after the release of `64.0.0`

[Link to Keywords docs section with PR docs](https://setuptools--3519.org.readthedocs.build/en/3519/references/keywords.html)

### Pull Request Checklist
- [x] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by abravalheri** [comment]
Thank you very much @evamaxfield, do you prefer to focus on the version of `setuptools`, or having a note similar to the one in the [pyproject.toml config page](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)?

**Comment by evamaxfield** [comment]
> Thank you very much @evamaxfield, do you prefer to focus on the version of `setuptools`, or having a note similar to the one in the [pyproject.toml config page](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)?

I think at least for a bit while it's a brand new feature, showing which versions support it or not is important - it should help with debugging 🤷‍♀️

**Comment by abravalheri** [comment]
It makes sense. Thank you very much.

**Comment by AppalachianBoomStick** [comment]
a600c16a0ccbb179a70da3a5dfb6aaf27200979d

**Pull request merged**
