### PR TITLE
Remove reliance on LegacyVersion

### LINKED ISSUE #2497: Remove support for LegacyVersion
In #2466 and pypa/packaging#368, it's become apparent that Setuptools should get out of the business of supporting the `LegacyVersion`.

### PR DESCRIPTION
**Pull request by jaraco**
- Remove use of packaging.version.LegacyVersion. Fixes #2497.
- Add changelog. Ref #2497.
- egg_info: avoid non-PEP440 versions from tag_date
- package_index: don't create dists with non-PEP440 versions
- Suppress the now invalid pbr version.
- Update test_egg_fragment to include a name with a dash in it. Expand on interpret_distro_name to be a tiny bit smarter about inferring the pivot separating name and version.

## Summary of changes

Closes #2497.

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.readthedocs.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by jaraco** [comment]
Good idea. In #2840, I introduce such a warning. I'd expected that introducing that warning would have happened from the packaging package, but because it's vendored and pinned, that warning has been suppressed.

**Comment by pradyunsg** [comment]
Hiya @jaraco! Anything I can do to help move this forward?

/cc @abravalheri as well. :)

**Comment by jaraco** [comment]
The deprecation has been in place for 15 months. Let's remove support.

**Review by pradyunsg — APPROVED** [review]
Not a setuptools maintainer, but LGTM!

**Pull request merged**
