### PR TITLE
Revert "drop easy_install script and associated documentation"

### PR DESCRIPTION
**Pull request by benoit-pierre**
This reverts commit 6e1838a9fb5feb000ba9b6a3c37c8b39d7e872b3.

### CODE REVIEW

**Comment by benoit-pierre** [comment]
Also added changelog entries for this and #1830.

**Comment by jaraco** [comment]
Thanks @benoit-pierre for putting this together. I wonder if we can avoid re-adding this functionality by instead moving it to another package (called easy_install), and having setuptools depend on that package. That decoupling would make it obvious what is deprecated and provide a path to backward compatibility (those requiring/expecting this functionality could retain it by installing `easy_install` separately).

My main reluctance for doing this is that by adding a dependency, that dependency becomes non-optional (`pkg_resources` will expect the `easy_install` package to be present and crash if it's not).

Let me put together a draft.

**Comment by pganssle** [comment]
@jaraco I think that might overly complicate things. Even in the now-reverted change, all the old functionality was preserved, we just had removed one of the public interfaces. We can just add a new wrapper script that warns that it's deprecated and in say 1 year replace it with one that actually raises an exception, same way we've done for `upload` and `register `.

I think there will be very little ongoing support burden to ship a script that just raises an exception, so we should probably just do the lowest-effort thing that gets us to that endpoint without introducing any footguns for end users.

**Comment by jaraco** [comment]
You make a good argument. I think I agree.

I did throw together the [easy_install package](/pypa/easy_install). All it needs is a tag to cut a release, but I'll refrain from doing that if we're not going to use it.

**Comment by jaraco** [comment]
In #1913, I drafted my concept, but right away it reveals issues (with bootstrapping), at least one of the foot guns. Let's proceed with this approach for now.

**Pull request merged**
