### PR TITLE
Improvements for declarative configuration

### PR DESCRIPTION
**Pull request by idlesign**
Hi,

1. `read_configuration()` now accepts `ignore_option_errors` argument. This allows scraping tools to read metadata without a need to download entire packages. E.g. we can gather some stats right from GitHub repos just by downloading `setup.cfg`.

2. `packages` `find:` directive now supports fine tuning from a subsection. The same arguments as for `find()` are accepted.

### CODE REVIEW

**Comment by idlesign** [comment]
Fails on unrelated:

`test_mixed_site_and_non_site`
`test_links_priority`
`test_setup_requires_honors_fetch_params`

**Comment by idlesign** [comment]
`test_setup_requires_honors_fetch_params` fail is fixed.

Yet seem to fail in master somehow:
`test_mixed_site_and_non_site` 
`test_links_priority`

**Comment by idlesign** [comment]
@jaraco Fixed. This one was specific for test environment.

**Comment by jaraco** [comment]
I've rebased your commits onto the rolled-back master, now terminating at c471788db.

**Pull request closed without merging**
