### PR TITLE
Add 3.6-dev and nightly to travis configuration

### PR DESCRIPTION
**Pull request by xavfernandez**

### CODE REVIEW

**Comment by xavfernandez** [comment]
Hmmm, I was hopinh the tests to crash on 3.6 and 3.7 since pip test suite on these versions triggers an error on `from pkg_resources import Distribution, PathMetadata, ensure_directory` (cf https://travis-ci.org/pypa/pip/jobs/167948406).

Anyway, even if tests pass, it does not hurt to test setuptools on coming versions.

**Comment by jaraco** [comment]
I'll put pypy3 back as well, that's a supported configuration.

**Comment by xavfernandez** [comment]
oops, I must have deleted pypy3 without noticing.
Any clue on https://travis-ci.org/pypa/pip/jobs/167948406 crash ?

**Comment by jaraco** [comment]
I don't really have a clue on either of those failures. I do see the second failure occurs in setuptools, but it's setuptools 0.9.8. Since tests pass on later versions of setuptools, my best guess is that the issue was addressed in later versions of setuptools... or that there's something that pip is doing to the environment that's breaking setuptools install.

**Comment by yan12125** [comment]
> Any clue on https://travis-ci.org/pypa/pip/jobs/167948406 crash ?

This seems the cause: https://github.com/pypa/virtualenv/issues/962

**Pull request merged**
