### PR TITLE
Add separate release workflow

### PR DESCRIPTION
**Pull request by blink1073**
## Summary of changes
Adds an extra discriminator for `${{ github.ref }}` in the concurrency group.
This avoids a race condition in workflow runs which caused the release job to be canceled for either a tag or a commit with the same sha.

Part of #3093 

### Pull Request Checklist
- [x] Changes have tests
- [ ] News fragment added in [`changelog.d/`].  N/A
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by abravalheri** [comment]
Hi @blink1073 thank you very much for providing this PR!

I was trying to go through GitHub's docs trying to understand this config with `release: types: [published]`.

Does this solve the problem with tests never running discussed in https://github.com/pypa/setuptools/issues/3093#issuecomment-1041535777?

**Comment by blink1073** [comment]
The latest commit effectively restores the original behavior before concurrency limiting as much as possible.   The only difference is that we don't run the unit tests explicitly before release.

**Comment by abravalheri** [comment]
I was not expecting how **more** annoying PyPy+Windows tests can be...
It is like they are just waiting to fail in different ways...

**Comment by blink1073** [comment]
Yeah, it is pain squared

**Comment by blink1073** [comment]
Okay, with the latest change I believe we have what we want.  We avoid canceling subsequent pushes *and* pushes that are to different git references, `refs/head/main` vs `refs/tags/foo`.

**Comment by blink1073** [comment]
Closing in favor of #3116

**Pull request closed without merging**
