### PR TITLE
tests: temporary pin pip to fix the Python 2.7 job

### PR DESCRIPTION
**Pull request by benoit-pierre**
Temporary fix for #1644.

### CODE REVIEW

**Comment by jaraco** [comment]
LGTM

**Comment by jaraco** [comment]
We should add a comment to the pip pin so it references the relevant issue.

**Comment by benoit-pierre** [comment]
> We should add a comment to the pip pin so it references the relevant issue.

Done.

**Comment by jaraco** [comment]
Perfect.

**Pull request merged**
