### PR TITLE
Added the namespace_packages argument to find_packages()

### PR DESCRIPTION
**Pull request by agronholm**
This allows find_packages() to work with PEP 420 namespace packages without considering every directory a namespace package.

### CODE REVIEW

**Comment by agronholm** [comment]
Only after submitting this, I learned about `find:`. I would really like to make this work with the `namespace_packages` argument in setup(), but it requires it to be parsed before `packages`. For this to happen, the parsers in `ConfigOptionsHandler` need to be processed in a deterministic order, for which `OrderedDict` is required. This would not be a problem if setuptools wasn't still trying to support Python 2.6. Would it be possible to drop this support, as it has been EOL'd quite some time ago?

**Comment by estan** [comment]
Looks similar to the #915 I submitted back in February, but maybe a little more elegant.

My PR was rejected by @jaraco back then, since he felt discussion was active on #97. That issue has been silent since then though, so I guess perhaps it's time to just accept the state of things and go ahead with a `namespace_packages=` solution. What do you think @jaraco?

**Comment by estan** [comment]
Personally, I'd say that's a better solution than having a growing number of people adding their own ad-hoc `find_packages` alongside their `setup.py`.

**Comment by estan** [comment]
@agronholm What does `find:` in your comment mean (I've been out of the loop for a while).

**Comment by agronholm** [comment]
It means that you can now do `packages='find:` which is equivalent to `packages=find_packages()`, but you can use that when specifying packages under `[metadata]` in your setup.cfg. The obvious advantage is that you could reuse the (otherwise useless on py3) `namespace_packages` option with that one.

**Comment by estan** [comment]
@agronholm Ah, I see.

**Comment by jaraco** [comment]
> Would it be possible to drop this support, as it has been EOL'd quite some time ago?

See #878 for rationale for Python 2.6 support.

> I would really like to make this work with the namespace_packages argument in setup()

Me too.

> OrderedDict is required

Although Setuptools can't accept dependencies naturally, it does have a well-defined way to vendor dependencies, so that is an option.

But it sounds as if the optimal approach here might be to use what you've envisioned, re-using the namespace_packages directive. I much prefer that because it's less duplicative.

Because this change does affect the way packagers' interface, it will have long-lasting effects, so I want to be sure to select the best approach before proceeding.

Let's come to an enthusiastic consensus in #97 and then proceed with an implementation.

**Comment by agronholm** [comment]
To me, this seems to ultimately hinge on pip's continued support of Python 2.6. When that's gone, #878 can be resolved and with that, we won't have to vendor OrderedDict and can proceed with this PR. Right?

**Comment by jaraco** [comment]
This PR as presented doesn't depend on OrderedDict unless the suggested adaptation is made, in which case, dropping Python 2.6 does help with that. I'm also willing to accept a vendored library for ordered dict to add that support with Python 2.6 support.

But I did realize later there's another issue with relying on the `namespace_packages` declaration in the call to `setup`, and that's that the use of `namespace_packages` is [discouraged](https://python-packaging-user-guide.readthedocs.io/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages).

This all leads me to believe that this explicit though sometimes duplicative declaration indicated in this PR as is may be the the best option.

**Comment by agronholm** [comment]
> This all leads me to believe that this explicit though sometimes duplicative declaration indicated in this PR as is may be the the best option.

I disagree. These days I use setup.cfg exclusively for specifying metadata and most setup options too. Now what happens if only find_packages() gets the namespace package finding feature? I'm screwed again.

**Comment by agronholm** [comment]
What is the problem with repurposing `namespace_packages` for use with `find:`? It's even backwards compatible when used this way, yes? We don't **have** to create any placeholder `__init__.py` files on Python 3 when this option is given, do we?

**Comment by jaraco** [comment]
IIRC, if you currently specify `setup(namespace_packages=[...])`, those directories must contain `pkg_resources.declare_namespace` or setuptools will reject it. Perhaps based on the newer recommendations, we should drop that constraint.

**Comment by agronholm** [comment]
Right, at least I don't see any other good way to make namespace packages work with `find:`. If you have a better idea, I'm all ears.

**Comment by agronholm** [comment]
I think that might warrant an entirely new PR though, rather than trying to shoehorn it into this one.

**Comment by jaraco** [comment]
Okay. Let's continue the discussion in #97.

**Pull request closed without merging**
