### PR TITLE
Add setuptools.command.build

### PR DESCRIPTION
**Pull request by isuruf**
## Summary of changes

In order to override distutils.command.build on downstream projects
it is good to have a setuptools specific command which allows
downstream projects to avoid importing distutils.

Closes 

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by abravalheri** [comment]
Thank you very much @isuruf, sorry for the confusion with the extra commits, I was trying to fix the error with `flake8`, I hope that is OK with you.

I am OK with this change, but I will let the other maintainers have a look because I don't know if there are other implications.

**Comment by isuruf** [comment]
Ping on this

**Comment by abravalheri** [comment]
Thank you very much @isuruf and sorry for the delay.
Since no one has found any problem with this implementation, I believe we can go ahead...

Should we add any protection/migration warnings for the case an user was previously relying on `distutils.command.build` to setup subcommands?

For example, how about something like:

```python
_ORIGINAL_SUBCOMMANDS = {"build_py", "build_clib", "build_ext", "build_scripts"}

class build(_build):
    def run(self):
       subcommands = {cmd[0] for cmd in _build.sub_commands}
       if subcommands - _ORIGINAL_SUBCOMMANDS:
           msg = """
           It seems that you are using `distutils.command.build.build` to add new subcommands.
           Using `distutils` directly is considered deprecated, please use `setuptools.command.build`.
           """
           warning.warns(msg, SetuptoolsDeprecationWarning)
           self.subcommands = _build.sub_commands
       super().run()
  ...
```

What do you think?

**Comment by abravalheri** [comment]
Thank you very much @isuruf and sorry for the delay.
Since no one has found any problem with this implementation, I believe we can go ahead...

Should we add any protection/migration warnings for the case an user was previously relying on `distutils.command.build` to setup subcommands?

For example, how about something like:

```python
_ORIGINAL_SUBCOMMANDS = {"build_py", "build_clib", "build_ext", "build_scripts"}

class build(_build):
    def run(self):
       subcommands = {cmd[0] for cmd in _build.sub_commands}
       if subcommands - _ORIGINAL_SUBCOMMANDS:
           msg = """
           It seems that you are using `distutils.command.build.build` to add new subcommands.
           Using `distutils` directly is considered deprecated, please use `setuptools.command.build`.
           """
           warning.warns(msg, SetuptoolsDeprecationWarning)
           self.subcommands = _build.sub_commands
       super().run()
  ...
```

What do you think?

**Comment by isuruf** [comment]
Makes sense to me. There's a small typo in the line before last. `self.subcommands` should be `self.sub_commands`. Can you push into this PR or should I?

**Comment by abravalheri** [comment]
I can do that later today, but if you would like to go ahead and work on it, that would be great (since I would have to spend some time to create a simple test case).

**Comment by abravalheri** [comment]
Hi @isuruf, I tried to fix the tests failing in the CI.
Please feel free to revert my changes and do something different.

**Pull request merged**
