### PR TITLE
Fixed a bug that easy install incorrectly parsed Python 3.10 version string

### PR DESCRIPTION
**Pull request by liuzhe-lz**
## Summary of changes

Fixed a bug that easy install incorrectly parsed Python 3.10 version string.

### Pull Request Checklist
- [x] Changes have tests
- [x] News fragment added in [`changelog.d/`].
  _(See [documentation][PR docs] for details)_

[`changelog.d/`]: https://github.com/pypa/setuptools/tree/master/changelog.d
[PR docs]:
https://setuptools.pypa.io/en/latest/development/developer-guide.html#making-a-pull-request

### CODE REVIEW

**Comment by jaraco** [comment]
Looks like this bug was reported in #3001.

Can you add a test?

**Comment by liuzhe-lz** [comment]
Sorry I don't have time for now.
Maybe you can help add one. Or I can do it sometime next week.

> Looks like this bug was reported in #3001.
> 
> Can you add a test?

Sorry I don't have time for now.
Maybe you can help add one. Or I can do it sometime next week.

**Comment by abravalheri** [comment]
As the existing tests are not running properly, I think the best here would be an update, So here it goes...

@Mergifyio update

**Comment by abravalheri** [comment]
Hi @liuzhe-lz, @jaraco I added some tests to the proposed fix. Please feel free to remove it, change or add any other tests.

(I also reordered a bit the commits, because I wanted to see the test failing before the fix is applied and study how to better represent the situation in #3001).

---

Notes:

I noticed the `stdlib` version of distutils sometimes create a path that contains a literal string `'None'`, which seems to be a bug already solved in the vendored version.

Another thing that I noticed is that for Windows 3.10, there might be a `ValueError: invalid variable 'py_version_nodot_plat'`, which I guess is already solved by https://github.com/pypa/distutils/commit/1560a1fe4e56e00392d3658a59e6fc7238e26a8a and will be eventually pulled into `setuptools`.

**Comment by jaraco** [comment]
Thanks everyone!

**Pull request merged**
