### PR TITLE
Speed up console_ and gui_scripts

### PR DESCRIPTION
**Pull request by untitaker**
See #510

- [ ] Add testcase for `my_mod:MyClass.my_func` entrypoint (where to put it?)

### CODE REVIEW

**Comment by untitaker** [comment]
Is there a possibility that some sort of changes entry points at runtime? Because then we might not be able to resolve and import them at this point.

**Comment by jaraco** [comment]
I know one case where this will definitely break - `multi-version installs`. If you use `easy_install --multi-version` to install your package, the package won't be visible on `__import__` without first being `required`, which is part of what `load_entry_point` does.

I also worry that all of this effort is for nothing since `easy_install` is largely deprecated in favor of installing with pip, which uses distlib, and [simply relying on distlib in easy_install scripts](https://github.com/pypa/setuptools/pull/595) as well.

Considering the backward-incompatibility concerns here and the fact that it conflicts with the preferred approach, I'd rather suggest that we focus on advancing the work started in #595.

**Comment by untitaker** [comment]
>If you use easy_install --multi-version to install your package, the package won't be visible on __import__ without first being required, which is part of what load_entry_point does.

I see. Could we use the old logic for `easy_install` and this one for `pip`? Such that only scripts that are installed through pip get this speedup.

>I also worry that all of this effort is for nothing since easy_install is largely deprecated in favor of installing with pip

This PR has a direct effect on the scripts `pip install -e` produces.

I don't see how #595 is related.

**Comment by jaraco** [comment]
If one were to use distlib to install scripts, those scripts would behave the same as those installed by pip.

**Comment by untitaker** [comment]
That's a lot of ifs there. I don't understand whether it is possible to install
scripts using distlib at the moment.

**Comment by jaraco** [comment]
> Could we use the old logic for easy_install and this one for pip?

Isn't it the case that only scripts installed by easy_install are affected by this issue?

**Comment by untitaker** [comment]
No, this PR is about "pip install". I didn't test easy_install manually.

**Comment by ninjaaron** [comment]
pip install will use the easy_install module internally unless the the package was built with wheel.

as far as I know, there is no good way to do it with `pip install -e` (though I'm sure someone will correct me if I'm wrong). you have to do something like `pip wheel .; pip install .` to get the benefits of distlib with pip on a local project. The alternative would be to use your own loader script in the project directory. (or use [fastentrypoints](https://github.com/ninjaaron/fast-entry_points), of course!)

**Comment by jaraco** [comment]
> No, this PR is about "pip install". I didn't test easy_install manually.

Well, when I use `pip install`, it installs the packages without the `pkg_resources` hooks.

```
$ pip install --user --no-binary :all: pytest 
Collecting pytest
  Downloading pytest-3.0.5.tar.gz (740kB)
    100% |████████████████████████████████| 747kB 1.6MB/s 
Requirement already satisfied: py>=1.4.29 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pytest)
Installing collected packages: pytest
  Running setup.py install for pytest ... done
Successfully installed pytest-3.0.5
$ cat Library/Python/3.6/bin/py.test               
#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pytest==3.0.5','console_scripts','py.test'
__requires__ = 'pytest==3.0.5'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pytest==3.0.5', 'console_scripts', 'py.test')()
    )
```

I think that's because `pip install` will build from the sdist a wheel and install it if no wheel is available (or if binaries are excluded).

It sounds like what you're talking about is `pip install -e`, which under the hood just invokes `setup.py develop` which itself invokes `easy_install`.

Since this issue only affects `develop` installs and not normal installs, it seems largely mitigated by the recommendation to primarily use `pip install`.

I'd like to focus the remaining energy we have onto some of the larger goals, such as removing easy_install. One step that will have to take place to remove easy_install is to solve the `setup.py develop`/`pip install -e` use case, preferably in a library that pip or setuptools can invoke (probably packaging+distlib, but maybe just distlib). Solving that would reduce pip's dependency on setuptools but will also solve this issue.

@vsajip, @dstufft: Do you have any opinion on where the logic for "in-place installs" (as currently implemented in setup.py develop) should go?

**Comment by dstufft** [comment]
@jaraco Honestly, I think the best thing to do is to continue to have setuptools handle this, and wait until the PEPs for abstract build systems come to completion and let the standardization process hammer out who should be responsible for what in terms of in place builds.

**Comment by hobarrera** [comment]
@dstufft TBH, that's too long-term. We're currently dealing with an issue of very slow start-ups (for a 200ms app, the start-up is an additional ~900ms for me).
I'm also constantly seeing reports of slowness at start-up for my projects and others I follow.

While I think it's great that at some point in the future the standardization process gives an elegant solution for this, we really need some workaround or at least a not-so-elegant fix for this in the meantime.

Maybe an extra `setup.py` flag to *not* use `pkg_resources` and do a plain ol' import would suffice for now (at least for those who don't need the multi-version support).

**Comment by dstufft** [comment]
@hobarrera If your users are installing using pip, the only time they should get the slow down is they are not installing from a wheel.

**Comment by hobarrera** [comment]
> If your users are installing using pip, the only time they should get the slow down is they are not installing from a wheel.

I can't really control how users install. TBH, most (including myself) use the distribution packages, which use `python setup.py install`.

I can try and convince packagers of my packages to start using wheels, but that will only affect a few packages for my own projects, and not others (like I said: some apps I use/follow have the same issue, though I'm not a dev there).

**Pull request closed without merging**
