### PR TITLE
Don't check if dist is an instance of distutils.dist.Distribution, its not

### PR DESCRIPTION
**Pull request by JensTimmerman**
based on this patch for Distutils (but we can't patch distutils in old python versions can we?)
http://bugs.python.org/issue23102

Whilst we wait for this to get merged into python, it could be fixed this way for setuptools?

### CODE REVIEW

**Comment by JensTimmerman** [comment]
relates to #73

**Comment by JensTimmerman** [comment]
```
#!/usr/bin/env python
''' Installation script that breaks '''

from distutils.command import install
from distutils.core import setup

class installer(install.install):
    def run(self):
        import setuptools
        install.install.run(self)


setup(name='test',
      cmdclass = dict(install=installer)
     )

```
run with: 
python setup.py install --user
result:
```
running install
running build
running install_egg_info
Traceback (most recent call last):
  File "mysetup.py", line 14, in <module>
    cmdclass = dict(install=installer)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "mysetup.py", line 10, in run
    install.install.run(self)
  File "/usr/lib64/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 970, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
```
expected result:
```
running install
running build
running install_egg_info
Writing /home/jens/.local/lib/python2.7/site-packages/test-0.0.0-py2.7.egg-info
```

it seems like this might get fixed in newer distutil releases:
http://bugs.python.org/issue23102

**Comment by jaraco** [comment]
My instinct is to say that this attempted usage of setuptools is not supported.

Can you explain more why the code goes through those contortions to avoid importing setuptools until late?

**Comment by JensTimmerman** [comment]
The code goes trought these contortions to be a small example that fits in a single file.

It just happens every time a setuptools is imported at the wrong time, or when a distutils module is 
reloaded, or when a distutils Command object is patched before setuptools patches it, or if setuptools does patch it but then get's reloaded.

A lot of projects have made this error in the past, and it is pretty hard to debug, usually you don't hit the error in your application, but when one of your dependencies imports setuptools to early.

a list of projects who have run into this:
https://github.com/pypa/setuptools/issues/85
https://github.com/pypa/setuptools/issues/73
http://stackoverflow.com/questions/21136266/typeerror-dist-must-be-a-distribution-instance-when-resolving-beautifulsoup-d
https://github.com/numpy/numpy/issues/7235
https://bugs.launchpad.net/pbr/+bug/1412875
https://bugs.launchpad.net/pbr/+bug/1324784
https://groups.google.com/forum/#!topic/cython-users/VP44IsQrJ60
https://ask.openstack.org/en/question/5478/how-do-i-work-around-the-typeerror-dist-must-be-a-distribution-instance-problem-when-following-the-swift-all-in-one-instructions/
https://github.com/pypa/setuptools/issues/73#issuecomment-247829987
http://lists.science.uu.nl/pipermail/nix-dev/2014-July/013591.html
https://www.mediawiki.org/wiki/Talk:Continuous_integration/Jenkins_job_builder
http://www.gossamer-threads.com/lists/openstack/dev/36874
https://mail.scipy.org/pipermail/scipy-dev/2008-September/009736.html
https://jira.opnfv.org/browse/STORPERF-35
https://twitter.com/simonmcc/status/473490398145298432

the list goes on and on, just google for the error message, people usually get frustrated in python, and barely have any idea how to resolve this issue.
Usually it's either: make sure setuptools is imported earlier, or make sure setuptools is imported later

Read trought a few of the above links to get an idea of how frustrated people can get about this, 
it also took me 3 months of trying all sorts of different things before I found out I just had to import setuptools later in my case, not earlier.

**Comment by jaraco** [comment]
Oh, I think I missed that this was patched in distutils. Yes, setuptools add forward compatibility for what distutils offers.

Can you implement it slightly differently -- copy the code from distutils byte-for-byte into a separate method and commit that change so that we can track any changes that are made to that code. Add a comment indicating from where the code was taken (e.g. Python 3.6.0b1 distutils/cmd.py), and then call that from the original method (keeping separate the divergent behavior), and finally, call the version in distutils directly if it's known to have been patched. This way, when our future selves return to this function, we'll be able to ascertain what was done, why it was done, and when the compatibility layer can be dropped.

**Comment by jaraco** [comment]
Reviewing the upstream bug, it seems like it hasn't been fixed yet, but will be soon. Let's focus on getting the issue patched in distutils, and then prepare a backport in Setuptools based on that implementation and using the technique I describe above.

**Comment by dabliss** [comment]
what is the status with this?  i see the issue's been closed, but i just encountered this error, and i have no idea how to fix it.  @JensTimmerman did a great job above reviewing ways in which people have encountered this error and some hack solutions for it . . . but what is the final, correct, general way to avoid this error?

**Pull request closed without merging**
